// Generated by nitrogen — public exports for the NitroWebgpuPresentCpp SPM target.
// Re-exports the Dart DL API from the NitroWebgpuCpp dependency.
// Deliberately NOT named NitroWebgpuPresentCpp.h: SwiftPM would treat that as the
// umbrella header and reject any subdirectory next to it (issue #21).
#include "dart_api_dl.h"
