// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.5.12
// Generated from: nitro_webgpu.native.dart
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdlib.h>
#if defined(__APPLE__)
#import <Foundation/Foundation.h>
#endif
#if defined(__ANDROID__) || defined(__linux__)
#include <dlfcn.h>
#endif
#include "dart_api_dl.h"
#include "nitro_webgpu.bridge.g.h"

#if defined(_MSC_VER) && !defined(strdup)
#define strdup _strdup
#endif

extern "C" {
NITRO_EXPORT uint32_t nitro_webgpu_nitro_abi_version(void) {
    return 1;
}
NITRO_EXPORT const char* nitro_webgpu_nitro_bridge_checksum(void) {
    return "4792d7ab9819e4f4";
}
NITRO_EXPORT intptr_t nitro_webgpu_init_dart_api_dl(void* data) {
    return Dart_InitializeApiDL(data);
}
}
static thread_local NitroError g_nitro_error = { 0, nullptr, nullptr, nullptr, nullptr };

extern "C" {
NitroError* nitro_webgpu_get_error() { return &g_nitro_error; }
void nitro_webgpu_clear_error() {
    g_nitro_error.hasError = 0;
    if (g_nitro_error.name) { free((void*)g_nitro_error.name); g_nitro_error.name = nullptr; }
    if (g_nitro_error.message) { free((void*)g_nitro_error.message); g_nitro_error.message = nullptr; }
    if (g_nitro_error.code) { free((void*)g_nitro_error.code); g_nitro_error.code = nullptr; }
    if (g_nitro_error.stackTrace) { free((void*)g_nitro_error.stackTrace); g_nitro_error.stackTrace = nullptr; }
}

static void nitro_report_error(const char* name, const char* message, const char* code, const char* stack) {
    nitro_webgpu_clear_error();
    g_nitro_error.hasError = 1;
    g_nitro_error.name = name ? strdup(name) : strdup("NativeException");
    g_nitro_error.message = message ? strdup(message) : strdup("An unknown native exception occurred.");
    g_nitro_error.code = code ? strdup(code) : nullptr;
    g_nitro_error.stackTrace = stack ? strdup(stack) : nullptr;
}
}

#if defined(__ANDROID__) || defined(__linux__)
static void* _nitro_webgpu_lib_h = nullptr;
#endif

extern "C" {
// Finding 1: promotes this native library to process-wide visibility so that
// @Native<F>() Dart bindings resolve via DynamicLibrary.process() on Android/Linux.
// On iOS/macOS this is a no-op — symbols are already in the process namespace
// via static linking.  Call once from the Kotlin/Swift plugin init.
NITRO_EXPORT void nitro_webgpu_enable_native_bindings(void) {
#if defined(__ANDROID__) || defined(__linux__)
    if (!_nitro_webgpu_lib_h) {
        Dl_info info;
        if (dladdr((void*)nitro_webgpu_enable_native_bindings, &info) && info.dli_fname) {
            // RTLD_GLOBAL | RTLD_NOLOAD promotes already-loaded lib to global namespace
            // without re-loading it, making symbols available to DynamicLibrary.process().
            _nitro_webgpu_lib_h = dlopen(info.dli_fname, RTLD_LAZY | RTLD_GLOBAL | RTLD_NOLOAD);
        }
    }
#endif
}
}

#ifdef __ANDROID__
#include <jni.h>
#include <android/log.h>
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, "Nitrogen", __VA_ARGS__)

static JavaVM* g_jvm = nullptr;
static jclass g_bridgeClass = nullptr;

// ── Cached JNI IDs (initialized once in JNI_OnLoad, safe to use from any thread) ──
static jmethodID g_exc_getName = nullptr;
static jmethodID g_exc_getMessage = nullptr;
static jmethodID g_mid_create_instance_call = nullptr;
static jmethodID g_mid_destroy_instance_call = nullptr;
static jmethodID g_mid_add_call = nullptr;
static jmethodID g_mid_getGreeting_call = nullptr;


// RAII guard: auto-detaches a thread from the JVM when it exits.
// One instance is stored in thread-local storage; its destructor fires
// when the thread terminates, ensuring no JVM thread descriptor leaks.
struct NitroJniThreadGuard {
    bool attached = false;
    ~NitroJniThreadGuard() {
        if (attached && g_jvm != nullptr) {
            g_jvm->DetachCurrentThread();
        }
    }
};
static thread_local NitroJniThreadGuard g_thread_guard;

static void nitro_report_jni_exception(JNIEnv* env, jthrowable ex, NitroError* _nitro_err) {
    // MUST clear the pending exception before making any further JNI calls.
    // JNI aborts if any JNI function (e.g. GetObjectClass) is called while
    // an exception is still pending.
    env->ExceptionClear();
    jclass ex_class = env->GetObjectClass(ex);
    jstring j_name = (jstring)env->CallObjectMethod(ex_class, g_exc_getName);
    const char* name = (j_name != nullptr) ? env->GetStringUTFChars(j_name, 0) : "JavaException";

    jstring j_msg = (jstring)env->CallObjectMethod(ex, g_exc_getMessage);
    const char* msg = (j_msg != nullptr) ? env->GetStringUTFChars(j_msg, 0) : "No message provided";

    // S8: write to out-param slot (sync) or TLS slot (async, _nitro_err == nullptr).
    if (_nitro_err) {
        _nitro_err->hasError = 1;
        _nitro_err->name       = strdup(name);
        _nitro_err->message    = strdup(msg);
        _nitro_err->code       = nullptr;
        _nitro_err->stackTrace = nullptr;
    } else {
        // Async functions use TLS slot (read by callAsync via get_error/clear_error).
        nitro_report_error(name, msg, nullptr, nullptr);
    }

    if (j_name) {
        env->ReleaseStringUTFChars(j_name, name);
        env->DeleteLocalRef(j_name);
    }
    if (j_msg) {
        env->ReleaseStringUTFChars(j_msg, msg);
        env->DeleteLocalRef(j_msg);
    }
    env->DeleteLocalRef(ex_class);
    env->DeleteLocalRef(ex);
}


extern "C" {

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void* reserved) {
    g_jvm = vm;
    __android_log_print(ANDROID_LOG_INFO, "Nitrogen", "JNI_OnLoad called for nitro_webgpu");
    JNIEnv* env = nullptr;
    if (vm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6) != JNI_OK) {
        return -1;
    }
    // Cache standard-library method IDs only — system class loader is always
    // available here. Application class IDs are deferred to initialize().
    {
        jclass cls_class = env->FindClass("java/lang/Class");
        if (cls_class) { g_exc_getName = env->GetMethodID(cls_class, "getName", "()Ljava/lang/String;"); env->DeleteLocalRef(cls_class); }
        jclass throwable_class = env->FindClass("java/lang/Throwable");
        if (throwable_class) { g_exc_getMessage = env->GetMethodID(throwable_class, "getMessage", "()Ljava/lang/String;"); env->DeleteLocalRef(throwable_class); }
    }
    return JNI_VERSION_1_6;
}

static JNIEnv* GetEnv() {
    if (g_jvm == nullptr) { return nullptr; }
    JNIEnv* env = nullptr;
    int status = g_jvm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);
    if (status == JNI_EDETACHED) {
        g_jvm->AttachCurrentThread(&env, nullptr);
        g_thread_guard.attached = true; // will DetachCurrentThread on thread exit
    }
    return env;
}

NITRO_EXPORT void nitro_webgpu_nitro_free(void* ptr) { if (ptr) { free(ptr); } }
NITRO_EXPORT void* nitro_webgpu_nitro_alloc(size_t size) { return malloc(size); }

NITRO_EXPORT int64_t nitro_webgpu_create_instance(const char* key) {
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return -1; }
    jmethodID mid = g_mid_create_instance_call;
    if (mid == nullptr) { LOGE("create_instance_call JNI method not cached"); return -1; }
    jstring j_key = env->NewStringUTF(key ? key : "default");
    jlong id = env->CallStaticLongMethod(g_bridgeClass, mid, j_key);
    env->DeleteLocalRef(j_key);
    if (env->ExceptionCheck()) { env->ExceptionClear(); LOGE("create_instance_call threw"); return -1; }
    return (int64_t)id;
}

NITRO_EXPORT void nitro_webgpu_destroy_instance(int64_t instanceId) {
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return; }
    jmethodID mid = g_mid_destroy_instance_call;
    if (mid == nullptr) { LOGE("destroy_instance_call JNI method not cached"); return; }
    env->CallStaticVoidMethod(g_bridgeClass, mid, (jlong)instanceId);
    if (env->ExceptionCheck()) { env->ExceptionClear(); }
}

double nitro_webgpu_add(int64_t instanceId, double a, double b, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return 0.0; }
    jmethodID methodId = g_mid_add_call;
    if (methodId == nullptr) { LOGE("Method not found: add_call sig=(JDD)D"); return 0.0; }

    nitro_webgpu_clear_error();
    if (env->PushLocalFrame(16) != 0) { return 0.0; }
    double res = env->CallStaticDoubleMethod(g_bridgeClass, methodId, (jlong)instanceId, a, b);
    if (env->ExceptionCheck()) {
        nitro_report_jni_exception(env, env->ExceptionOccurred(), _nitro_err);
        env->PopLocalFrame(nullptr);
        return 0.0;
    }
    env->PopLocalFrame(nullptr);
    return res;
}

const char* nitro_webgpu_get_greeting(int64_t instanceId, const char* name) {
    NitroError* _nitro_err = nullptr; // async: errors use TLS not out-param
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return nullptr; }
    jmethodID methodId = g_mid_getGreeting_call;
    if (methodId == nullptr) { LOGE("Method not found: getGreeting_call sig=(JLjava/lang/String;)Ljava/lang/String;"); return nullptr; }

    nitro_webgpu_clear_error();
    if (env->PushLocalFrame(16) != 0) { return nullptr; }
    jstring j_name = env->NewStringUTF(name);
    jstring jstr = (jstring)env->CallStaticObjectMethod(g_bridgeClass, methodId, (jlong)instanceId, j_name);
    if (env->ExceptionCheck()) {
        nitro_report_jni_exception(env, env->ExceptionOccurred(), _nitro_err);
        env->PopLocalFrame(nullptr);
        return nullptr;
    }
    if (jstr == nullptr) {
        env->PopLocalFrame(nullptr);
        return nullptr;
    }
    const char* nativeStr = env->GetStringUTFChars(jstr, 0);
    char* result = strdup(nativeStr);
    env->ReleaseStringUTFChars(jstr, nativeStr);
    env->PopLocalFrame(nullptr);
    return result;
}

JNIEXPORT void JNICALL Java_nitro_nitro_1webgpu_1module_NitroWebgpuJniBridge_initialize(JNIEnv* env, jobject thiz, jclass localClass) {
    if (g_bridgeClass == nullptr) {
        g_bridgeClass = (jclass)env->NewGlobalRef(localClass);
        env->DeleteLocalRef(localClass);
    }
    // Re-cache method IDs every time (safe; idempotent; works even if JNI_OnLoad
    // could not find the app class. initialize() is called from Kotlin with the
    // correct class loader.)
    if (g_bridgeClass != nullptr) {
        // Cache bridge method IDs
        // Each GetStaticMethodID is followed by an ExceptionClear() guard:
        // if ANY lookup fails it throws NoSuchMethodError, and calling the
        // NEXT GetStaticMethodID with a pending exception aborts the JVM on
        // Android >= API 26 (strict JNI mode). Clearing after each failure
        // lets the remaining lookups proceed and logs the missing method.
        g_mid_create_instance_call = env->GetStaticMethodID(g_bridgeClass, "create_instance_call", "(Ljava/lang/String;)J");
        if (!g_mid_create_instance_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: create_instance_call sig=(Ljava/lang/String;)J"); }
        g_mid_destroy_instance_call = env->GetStaticMethodID(g_bridgeClass, "destroy_instance_call", "(J)V");
        if (!g_mid_destroy_instance_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: destroy_instance_call sig=(J)V"); }
        g_mid_add_call = env->GetStaticMethodID(g_bridgeClass, "add_call", "(JDD)D");
        if (!g_mid_add_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: add_call sig=(JDD)D"); }
        g_mid_getGreeting_call = env->GetStaticMethodID(g_bridgeClass, "getGreeting_call", "(JLjava/lang/String;)Ljava/lang/String;");
        if (!g_mid_getGreeting_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: getGreeting_call sig=(JLjava/lang/String;)Ljava/lang/String;"); }
    }

}

} // extern "C"
#elif __APPLE__
extern "C" {
extern double _nitro_webgpu_call_add(double a, double b);
double nitro_webgpu_add(int64_t instanceId, double a, double b, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }
#ifdef __OBJC__
    @try {
        return _nitro_webgpu_call_add(a, b);
    } @catch (NSException* e) {
        if (_nitro_err) {
            // sync: write exception to out-param error slot.
            _nitro_err->hasError = 1;
            _nitro_err->name    = strdup([e.name UTF8String]);
            _nitro_err->message = strdup([e.reason UTF8String]);
            _nitro_err->code = nullptr;
            _nitro_err->stackTrace = nullptr;
        } else {
            // async: _nitro_err is null — route exception to TLS slot.
            nitro_report_error([e.name UTF8String], [e.reason UTF8String], nullptr, nullptr);
        }
        return 0.0;
    }
#else
    return _nitro_webgpu_call_add(a, b);
#endif
}

extern const char* _nitro_webgpu_call_getGreeting(const char* name);
const char* nitro_webgpu_get_greeting(int64_t instanceId, const char* name) {
    NitroError* _nitro_err = nullptr; // async: errors use TLS not out-param
#ifdef __OBJC__
    @try {
        return _nitro_webgpu_call_getGreeting(name);
    } @catch (NSException* e) {
        if (_nitro_err) {
            // sync: write exception to out-param error slot.
            _nitro_err->hasError = 1;
            _nitro_err->name    = strdup([e.name UTF8String]);
            _nitro_err->message = strdup([e.reason UTF8String]);
            _nitro_err->code = nullptr;
            _nitro_err->stackTrace = nullptr;
        } else {
            // async: _nitro_err is null — route exception to TLS slot.
            nitro_report_error([e.name UTF8String], [e.reason UTF8String], nullptr, nullptr);
        }
        return nullptr;
    }
#else
    return _nitro_webgpu_call_getGreeting(name);
#endif
}

static int64_t nitro_webgpu_g_next_instance_id = 0;
NITRO_EXPORT int64_t nitro_webgpu_create_instance(const char* key) { (void)key; return nitro_webgpu_g_next_instance_id++; }
NITRO_EXPORT void nitro_webgpu_destroy_instance(int64_t instanceId) { (void)instanceId; }
NITRO_EXPORT void nitro_webgpu_nitro_free(void* ptr) { if (ptr) { free(ptr); } }
NITRO_EXPORT void* nitro_webgpu_nitro_alloc(size_t size) { return malloc(size); }

} // extern "C"
#elif defined(_WIN32) || defined(__linux__)  // Windows/Linux: NativeImpl.cpp — direct C++ dispatch
#include "nitro_webgpu.native.g.h"

static void _nitro_desktop_err(NitroError* _out, const char* _name, const char* _message) {
    nitro_report_error(_name, _message, nullptr, nullptr);
    if (_out) {
        _out->hasError = 1;
        _out->name = _name ? strdup(_name) : nullptr;
        _out->message = _message ? strdup(_message) : nullptr;
        _out->code = nullptr;
        _out->stackTrace = nullptr;
    }
}

static HybridNitroWebgpu* g_impl = nullptr;
static int64_t g_next_instance_id = 0;

extern "C" {
void nitro_webgpu_register_impl(HybridNitroWebgpu* impl) { g_impl = impl; }
HybridNitroWebgpu* nitro_webgpu_get_impl() { return g_impl; }
NITRO_EXPORT int64_t nitro_webgpu_create_instance(const char* key) { (void)key; return g_next_instance_id++; }
NITRO_EXPORT void nitro_webgpu_destroy_instance(int64_t instanceId) { (void)instanceId; }
NITRO_EXPORT void nitro_webgpu_nitro_free(void* ptr) { if (ptr) { free(ptr); } }
NITRO_EXPORT void* nitro_webgpu_nitro_alloc(size_t size) { return malloc(size); }

double nitro_webgpu_add(int64_t instanceId, double a, double b, NitroError* _nitro_err) {
    nitro_webgpu_clear_error();
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    if (!g_impl) { _nitro_desktop_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_webgpu_register_impl() first."); return 0.0; }
    try {
        return g_impl->add(a, b);
    } catch (const std::exception& e) {
        _nitro_desktop_err(_nitro_err, "CppException", e.what());
        return 0.0;
    } catch (...) {
        _nitro_desktop_err(_nitro_err, "CppException", "Unknown C++ exception");
        return 0.0;
    }
}

const char* nitro_webgpu_get_greeting(int64_t instanceId, const char* name) {
    nitro_webgpu_clear_error();
    if (!g_impl) { nitro_report_error("NotInitialized", "No C++ implementation registered. Call nitro_webgpu_register_impl() first.", nullptr, nullptr); return nullptr; }
    try {
        std::string _res = g_impl->getGreeting(std::string(name));
        return strdup(_res.c_str());
    } catch (const std::exception& e) {
        nitro_report_error("CppException", e.what(), nullptr, nullptr);
        return nullptr;
    } catch (...) {
        nitro_report_error("CppException", "Unknown C++ exception", nullptr, nullptr);
        return nullptr;
    }
}

} // extern "C"
#endif
