// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.5.12
// Generated from: nitro_webgpu_present.native.dart
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

#ifndef NITRO_EXPORT
#  if defined(_WIN32)
#    define NITRO_EXPORT __declspec(dllexport)
#  else
#    define NITRO_EXPORT __attribute__((visibility("default"))) __attribute__((used))
#  endif
#endif

#ifndef NITRO_ERROR_DEFINED
#define NITRO_ERROR_DEFINED
typedef struct {
  int8_t hasError;
  const char* name;
  const char* message;
  const char* code;
  const char* stackTrace;
} NitroError;
#endif

#ifndef NITRO_OPT_DEFINED
#define NITRO_OPT_DEFINED
#pragma pack(push, 1)
typedef struct { uint8_t hasValue; int64_t  value; } NitroOptInt64;
typedef struct { uint8_t hasValue; double   value; } NitroOptFloat64;
typedef struct { uint8_t hasValue; uint8_t  value; } NitroOptBool;
#pragma pack(pop)
#endif

#ifdef __cplusplus
extern "C" {
#endif

NITRO_EXPORT uint32_t nitro_webgpu_present_nitro_abi_version(void);
NITRO_EXPORT const char* nitro_webgpu_present_nitro_bridge_checksum(void);
NITRO_EXPORT intptr_t nitro_webgpu_present_init_dart_api_dl(void* data);
NITRO_EXPORT NitroError* nitro_webgpu_present_get_error(void);
NITRO_EXPORT void nitro_webgpu_present_clear_error(void);
NITRO_EXPORT int64_t nitro_webgpu_present_create_instance(const char* key);
NITRO_EXPORT void nitro_webgpu_present_destroy_instance(int64_t instanceId);
NITRO_EXPORT void nitro_webgpu_present_nitro_free(void* ptr);
NITRO_EXPORT void* nitro_webgpu_present_nitro_alloc(size_t size);



// Methods
NITRO_EXPORT int64_t nitro_webgpu_present_create_presenter(int64_t instanceId, int64_t deviceAddress, int64_t widthPx, int64_t heightPx, NitroError* _nitro_err);
NITRO_EXPORT int64_t nitro_webgpu_present_flutter_texture_id(int64_t instanceId, int64_t token, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_present_acquire_frame(int64_t instanceId, int64_t token, NitroError* _nitro_err, int64_t dart_port);
NITRO_EXPORT int64_t nitro_webgpu_present_acquire_frame_sync(int64_t instanceId, int64_t token, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_present_present_frame(int64_t instanceId, int64_t token, NitroError* _nitro_err);
NITRO_EXPORT int64_t nitro_webgpu_present_presenter_format(int64_t instanceId, int64_t token, NitroError* _nitro_err);
NITRO_EXPORT int8_t nitro_webgpu_present_presenter_uses_gpu_path(int64_t instanceId, int64_t token, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_present_resize_presenter(int64_t instanceId, int64_t token, int64_t widthPx, int64_t heightPx, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_present_presenter_set_surface_size(int64_t instanceId, int64_t token, int64_t widthPx, int64_t heightPx, NitroError* _nitro_err);
NITRO_EXPORT double nitro_webgpu_present_request_max_refresh_rate(int64_t instanceId, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_present_destroy_presenter(int64_t instanceId, int64_t token, NitroError* _nitro_err, int64_t dart_port);

#ifdef __cplusplus
}
#endif
