// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.5.12
// Generated from: nitro_webgpu_present.native.dart
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdlib.h>
#if defined(__APPLE__)
#import <Foundation/Foundation.h>
#endif
#if defined(__ANDROID__) || defined(__linux__)
#include <dlfcn.h>
#endif
#include "dart_api_dl.h"
#include "nitro_webgpu_present.bridge.g.h"

#if defined(_MSC_VER) && !defined(strdup)
#define strdup _strdup
#endif

extern "C" {
NITRO_EXPORT uint32_t nitro_webgpu_present_nitro_abi_version(void) {
    return 1;
}
NITRO_EXPORT const char* nitro_webgpu_present_nitro_bridge_checksum(void) {
    return "bf14d17dec7d2a0a";
}
NITRO_EXPORT intptr_t nitro_webgpu_present_init_dart_api_dl(void* data) {
    return Dart_InitializeApiDL(data);
}
}
static thread_local NitroError g_nitro_error = { 0, nullptr, nullptr, nullptr, nullptr };

extern "C" {
NitroError* nitro_webgpu_present_get_error() { return &g_nitro_error; }
void nitro_webgpu_present_clear_error() {
    g_nitro_error.hasError = 0;
    if (g_nitro_error.name) { free((void*)g_nitro_error.name); g_nitro_error.name = nullptr; }
    if (g_nitro_error.message) { free((void*)g_nitro_error.message); g_nitro_error.message = nullptr; }
    if (g_nitro_error.code) { free((void*)g_nitro_error.code); g_nitro_error.code = nullptr; }
    if (g_nitro_error.stackTrace) { free((void*)g_nitro_error.stackTrace); g_nitro_error.stackTrace = nullptr; }
}

static void nitro_report_error(const char* name, const char* message, const char* code, const char* stack) {
    nitro_webgpu_present_clear_error();
    g_nitro_error.hasError = 1;
    g_nitro_error.name = name ? strdup(name) : strdup("NativeException");
    g_nitro_error.message = message ? strdup(message) : strdup("An unknown native exception occurred.");
    g_nitro_error.code = code ? strdup(code) : nullptr;
    g_nitro_error.stackTrace = stack ? strdup(stack) : nullptr;
}
}

#if defined(__ANDROID__) || defined(__linux__)
static void* _nitro_webgpu_present_lib_h = nullptr;
#endif

extern "C" {
// Finding 1: promotes this native library to process-wide visibility so that
// @Native<F>() Dart bindings resolve via DynamicLibrary.process() on Android/Linux.
// On iOS/macOS this is a no-op — symbols are already in the process namespace
// via static linking.  Call once from the Kotlin/Swift plugin init.
NITRO_EXPORT void nitro_webgpu_present_enable_native_bindings(void) {
#if defined(__ANDROID__) || defined(__linux__)
    if (!_nitro_webgpu_present_lib_h) {
        Dl_info info;
        if (dladdr((void*)nitro_webgpu_present_enable_native_bindings, &info) && info.dli_fname) {
            // RTLD_GLOBAL | RTLD_NOLOAD promotes already-loaded lib to global namespace
            // without re-loading it, making symbols available to DynamicLibrary.process().
            _nitro_webgpu_present_lib_h = dlopen(info.dli_fname, RTLD_LAZY | RTLD_GLOBAL | RTLD_NOLOAD);
        }
    }
#endif
}
}

#ifdef __ANDROID__
#include <jni.h>
#include <android/log.h>
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, "Nitrogen", __VA_ARGS__)

static JavaVM* g_jvm = nullptr;
static jclass g_bridgeClass = nullptr;

// ── Cached JNI IDs (initialized once in JNI_OnLoad, safe to use from any thread) ──
static jmethodID g_exc_getName = nullptr;
static jmethodID g_exc_getMessage = nullptr;
static jmethodID g_mid_create_instance_call = nullptr;
static jmethodID g_mid_destroy_instance_call = nullptr;
static jmethodID g_mid_createPresenter_call = nullptr;
static jmethodID g_mid_flutterTextureId_call = nullptr;
static jmethodID g_mid_acquireFrame_call = nullptr;
static jmethodID g_mid_acquireFrameSync_call = nullptr;
static jmethodID g_mid_presentFrame_call = nullptr;
static jmethodID g_mid_presenterFormat_call = nullptr;
static jmethodID g_mid_presenterUsesGpuPath_call = nullptr;
static jmethodID g_mid_resizePresenter_call = nullptr;
static jmethodID g_mid_presenterSetSurfaceSize_call = nullptr;
static jmethodID g_mid_requestMaxRefreshRate_call = nullptr;
static jmethodID g_mid_destroyPresenter_call = nullptr;


// RAII guard: auto-detaches a thread from the JVM when it exits.
// One instance is stored in thread-local storage; its destructor fires
// when the thread terminates, ensuring no JVM thread descriptor leaks.
struct NitroJniThreadGuard {
    bool attached = false;
    ~NitroJniThreadGuard() {
        if (attached && g_jvm != nullptr) {
            g_jvm->DetachCurrentThread();
        }
    }
};
static thread_local NitroJniThreadGuard g_thread_guard;

static void nitro_report_jni_exception(JNIEnv* env, jthrowable ex, NitroError* _nitro_err) {
    // MUST clear the pending exception before making any further JNI calls.
    // JNI aborts if any JNI function (e.g. GetObjectClass) is called while
    // an exception is still pending.
    env->ExceptionClear();
    jclass ex_class = env->GetObjectClass(ex);
    jstring j_name = (jstring)env->CallObjectMethod(ex_class, g_exc_getName);
    const char* name = (j_name != nullptr) ? env->GetStringUTFChars(j_name, 0) : "JavaException";

    jstring j_msg = (jstring)env->CallObjectMethod(ex, g_exc_getMessage);
    const char* msg = (j_msg != nullptr) ? env->GetStringUTFChars(j_msg, 0) : "No message provided";

    // S8: write to out-param slot (sync) or TLS slot (async, _nitro_err == nullptr).
    if (_nitro_err) {
        _nitro_err->hasError = 1;
        _nitro_err->name       = strdup(name);
        _nitro_err->message    = strdup(msg);
        _nitro_err->code       = nullptr;
        _nitro_err->stackTrace = nullptr;
    } else {
        // Async functions use TLS slot (read by callAsync via get_error/clear_error).
        nitro_report_error(name, msg, nullptr, nullptr);
    }

    if (j_name) {
        env->ReleaseStringUTFChars(j_name, name);
        env->DeleteLocalRef(j_name);
    }
    if (j_msg) {
        env->ReleaseStringUTFChars(j_msg, msg);
        env->DeleteLocalRef(j_msg);
    }
    env->DeleteLocalRef(ex_class);
    env->DeleteLocalRef(ex);
}


extern "C" {

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void* reserved) {
    g_jvm = vm;
    __android_log_print(ANDROID_LOG_INFO, "Nitrogen", "JNI_OnLoad called for nitro_webgpu_present");
    JNIEnv* env = nullptr;
    if (vm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6) != JNI_OK) {
        return -1;
    }
    // Cache standard-library method IDs only — system class loader is always
    // available here. Application class IDs are deferred to initialize().
    {
        jclass cls_class = env->FindClass("java/lang/Class");
        if (cls_class) { g_exc_getName = env->GetMethodID(cls_class, "getName", "()Ljava/lang/String;"); env->DeleteLocalRef(cls_class); }
        jclass throwable_class = env->FindClass("java/lang/Throwable");
        if (throwable_class) { g_exc_getMessage = env->GetMethodID(throwable_class, "getMessage", "()Ljava/lang/String;"); env->DeleteLocalRef(throwable_class); }
    }
    return JNI_VERSION_1_6;
}

static JNIEnv* GetEnv() {
    if (g_jvm == nullptr) { return nullptr; }
    JNIEnv* env = nullptr;
    int status = g_jvm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);
    if (status == JNI_EDETACHED) {
        g_jvm->AttachCurrentThread(&env, nullptr);
        g_thread_guard.attached = true; // will DetachCurrentThread on thread exit
    }
    return env;
}

NITRO_EXPORT void nitro_webgpu_present_nitro_free(void* ptr) { if (ptr) { free(ptr); } }
NITRO_EXPORT void* nitro_webgpu_present_nitro_alloc(size_t size) { return malloc(size); }

NITRO_EXPORT int64_t nitro_webgpu_present_create_instance(const char* key) {
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return -1; }
    jmethodID mid = g_mid_create_instance_call;
    if (mid == nullptr) { LOGE("create_instance_call JNI method not cached"); return -1; }
    jstring j_key = env->NewStringUTF(key ? key : "default");
    jlong id = env->CallStaticLongMethod(g_bridgeClass, mid, j_key);
    env->DeleteLocalRef(j_key);
    if (env->ExceptionCheck()) { env->ExceptionClear(); LOGE("create_instance_call threw"); return -1; }
    return (int64_t)id;
}

NITRO_EXPORT void nitro_webgpu_present_destroy_instance(int64_t instanceId) {
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return; }
    jmethodID mid = g_mid_destroy_instance_call;
    if (mid == nullptr) { LOGE("destroy_instance_call JNI method not cached"); return; }
    env->CallStaticVoidMethod(g_bridgeClass, mid, (jlong)instanceId);
    if (env->ExceptionCheck()) { env->ExceptionClear(); }
}

int64_t nitro_webgpu_present_create_presenter(int64_t instanceId, int64_t deviceAddress, int64_t widthPx, int64_t heightPx, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return 0; }
    jmethodID methodId = g_mid_createPresenter_call;
    if (methodId == nullptr) { LOGE("Method not found: createPresenter_call sig=(JJJJ)J"); return 0; }

    nitro_webgpu_present_clear_error();
    if (env->PushLocalFrame(16) != 0) { return 0; }
    int64_t res = env->CallStaticLongMethod(g_bridgeClass, methodId, (jlong)instanceId, deviceAddress, widthPx, heightPx);
    if (env->ExceptionCheck()) {
        nitro_report_jni_exception(env, env->ExceptionOccurred(), _nitro_err);
        env->PopLocalFrame(nullptr);
        return 0;
    }
    env->PopLocalFrame(nullptr);
    return res;
}

int64_t nitro_webgpu_present_flutter_texture_id(int64_t instanceId, int64_t token, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return 0; }
    jmethodID methodId = g_mid_flutterTextureId_call;
    if (methodId == nullptr) { LOGE("Method not found: flutterTextureId_call sig=(JJ)J"); return 0; }

    nitro_webgpu_present_clear_error();
    if (env->PushLocalFrame(16) != 0) { return 0; }
    int64_t res = env->CallStaticLongMethod(g_bridgeClass, methodId, (jlong)instanceId, token);
    if (env->ExceptionCheck()) {
        nitro_report_jni_exception(env, env->ExceptionOccurred(), _nitro_err);
        env->PopLocalFrame(nullptr);
        return 0;
    }
    env->PopLocalFrame(nullptr);
    return res;
}

void nitro_webgpu_present_acquire_frame(int64_t instanceId, int64_t token, NitroError* _nitro_err, int64_t dart_port) {
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return; }
    jmethodID methodId = g_mid_acquireFrame_call;
    if (methodId == nullptr) { LOGE("Method not found: acquireFrame_call sig=(JJJJ)V"); return; }

    nitro_webgpu_present_clear_error();
    if (env->PushLocalFrame(16) != 0) { return; }
    env->CallStaticVoidMethod(g_bridgeClass, methodId, (jlong)instanceId, token, (jlong)(uintptr_t)_nitro_err, (jlong)dart_port);
    if (env->ExceptionCheck()) {
        nitro_report_jni_exception(env, env->ExceptionOccurred(), nullptr);
    }
    env->PopLocalFrame(nullptr);
}

int64_t nitro_webgpu_present_acquire_frame_sync(int64_t instanceId, int64_t token, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return 0; }
    jmethodID methodId = g_mid_acquireFrameSync_call;
    if (methodId == nullptr) { LOGE("Method not found: acquireFrameSync_call sig=(JJ)J"); return 0; }

    nitro_webgpu_present_clear_error();
    if (env->PushLocalFrame(16) != 0) { return 0; }
    int64_t res = env->CallStaticLongMethod(g_bridgeClass, methodId, (jlong)instanceId, token);
    if (env->ExceptionCheck()) {
        nitro_report_jni_exception(env, env->ExceptionOccurred(), _nitro_err);
        env->PopLocalFrame(nullptr);
        return 0;
    }
    env->PopLocalFrame(nullptr);
    return res;
}

void nitro_webgpu_present_present_frame(int64_t instanceId, int64_t token, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return; }
    jmethodID methodId = g_mid_presentFrame_call;
    if (methodId == nullptr) { LOGE("Method not found: presentFrame_call sig=(JJ)V"); return; }

    nitro_webgpu_present_clear_error();
    if (env->PushLocalFrame(16) != 0) { return; }
    env->CallStaticVoidMethod(g_bridgeClass, methodId, (jlong)instanceId, token);
    env->PopLocalFrame(nullptr);
    if (env->ExceptionCheck()) { nitro_report_jni_exception(env, env->ExceptionOccurred(), _nitro_err); }
}

int64_t nitro_webgpu_present_presenter_format(int64_t instanceId, int64_t token, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return 0; }
    jmethodID methodId = g_mid_presenterFormat_call;
    if (methodId == nullptr) { LOGE("Method not found: presenterFormat_call sig=(JJ)J"); return 0; }

    nitro_webgpu_present_clear_error();
    if (env->PushLocalFrame(16) != 0) { return 0; }
    int64_t res = env->CallStaticLongMethod(g_bridgeClass, methodId, (jlong)instanceId, token);
    if (env->ExceptionCheck()) {
        nitro_report_jni_exception(env, env->ExceptionOccurred(), _nitro_err);
        env->PopLocalFrame(nullptr);
        return 0;
    }
    env->PopLocalFrame(nullptr);
    return res;
}

int8_t nitro_webgpu_present_presenter_uses_gpu_path(int64_t instanceId, int64_t token, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return false; }
    jmethodID methodId = g_mid_presenterUsesGpuPath_call;
    if (methodId == nullptr) { LOGE("Method not found: presenterUsesGpuPath_call sig=(JJ)Z"); return false; }

    nitro_webgpu_present_clear_error();
    if (env->PushLocalFrame(16) != 0) { return false; }
    bool res = env->CallStaticBooleanMethod(g_bridgeClass, methodId, (jlong)instanceId, token);
    if (env->ExceptionCheck()) {
        nitro_report_jni_exception(env, env->ExceptionOccurred(), _nitro_err);
        env->PopLocalFrame(nullptr);
        return false;
    }
    env->PopLocalFrame(nullptr);
    return res;
}

void nitro_webgpu_present_resize_presenter(int64_t instanceId, int64_t token, int64_t widthPx, int64_t heightPx, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return; }
    jmethodID methodId = g_mid_resizePresenter_call;
    if (methodId == nullptr) { LOGE("Method not found: resizePresenter_call sig=(JJJJ)V"); return; }

    nitro_webgpu_present_clear_error();
    if (env->PushLocalFrame(16) != 0) { return; }
    env->CallStaticVoidMethod(g_bridgeClass, methodId, (jlong)instanceId, token, widthPx, heightPx);
    env->PopLocalFrame(nullptr);
    if (env->ExceptionCheck()) { nitro_report_jni_exception(env, env->ExceptionOccurred(), _nitro_err); }
}

void nitro_webgpu_present_presenter_set_surface_size(int64_t instanceId, int64_t token, int64_t widthPx, int64_t heightPx, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return; }
    jmethodID methodId = g_mid_presenterSetSurfaceSize_call;
    if (methodId == nullptr) { LOGE("Method not found: presenterSetSurfaceSize_call sig=(JJJJ)V"); return; }

    nitro_webgpu_present_clear_error();
    if (env->PushLocalFrame(16) != 0) { return; }
    env->CallStaticVoidMethod(g_bridgeClass, methodId, (jlong)instanceId, token, widthPx, heightPx);
    env->PopLocalFrame(nullptr);
    if (env->ExceptionCheck()) { nitro_report_jni_exception(env, env->ExceptionOccurred(), _nitro_err); }
}

double nitro_webgpu_present_request_max_refresh_rate(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return 0.0; }
    jmethodID methodId = g_mid_requestMaxRefreshRate_call;
    if (methodId == nullptr) { LOGE("Method not found: requestMaxRefreshRate_call sig=(J)D"); return 0.0; }

    nitro_webgpu_present_clear_error();
    if (env->PushLocalFrame(16) != 0) { return 0.0; }
    double res = env->CallStaticDoubleMethod(g_bridgeClass, methodId, (jlong)instanceId);
    if (env->ExceptionCheck()) {
        nitro_report_jni_exception(env, env->ExceptionOccurred(), _nitro_err);
        env->PopLocalFrame(nullptr);
        return 0.0;
    }
    env->PopLocalFrame(nullptr);
    return res;
}

void nitro_webgpu_present_destroy_presenter(int64_t instanceId, int64_t token, NitroError* _nitro_err, int64_t dart_port) {
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return; }
    jmethodID methodId = g_mid_destroyPresenter_call;
    if (methodId == nullptr) { LOGE("Method not found: destroyPresenter_call sig=(JJJJ)V"); return; }

    nitro_webgpu_present_clear_error();
    if (env->PushLocalFrame(16) != 0) { return; }
    env->CallStaticVoidMethod(g_bridgeClass, methodId, (jlong)instanceId, token, (jlong)(uintptr_t)_nitro_err, (jlong)dart_port);
    if (env->ExceptionCheck()) {
        nitro_report_jni_exception(env, env->ExceptionOccurred(), nullptr);
    }
    env->PopLocalFrame(nullptr);
}

JNIEXPORT void JNICALL Java_nitro_nitro_1webgpu_1present_1module_NitroWebgpuPresentJniBridge_initialize(JNIEnv* env, jobject thiz, jclass localClass) {
    if (g_bridgeClass == nullptr) {
        g_bridgeClass = (jclass)env->NewGlobalRef(localClass);
        env->DeleteLocalRef(localClass);
    }
    // Re-cache method IDs every time (safe; idempotent; works even if JNI_OnLoad
    // could not find the app class. initialize() is called from Kotlin with the
    // correct class loader.)
    if (g_bridgeClass != nullptr) {
        // Cache bridge method IDs
        // Each GetStaticMethodID is followed by an ExceptionClear() guard:
        // if ANY lookup fails it throws NoSuchMethodError, and calling the
        // NEXT GetStaticMethodID with a pending exception aborts the JVM on
        // Android >= API 26 (strict JNI mode). Clearing after each failure
        // lets the remaining lookups proceed and logs the missing method.
        g_mid_create_instance_call = env->GetStaticMethodID(g_bridgeClass, "create_instance_call", "(Ljava/lang/String;)J");
        if (!g_mid_create_instance_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: create_instance_call sig=(Ljava/lang/String;)J"); }
        g_mid_destroy_instance_call = env->GetStaticMethodID(g_bridgeClass, "destroy_instance_call", "(J)V");
        if (!g_mid_destroy_instance_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: destroy_instance_call sig=(J)V"); }
        g_mid_createPresenter_call = env->GetStaticMethodID(g_bridgeClass, "createPresenter_call", "(JJJJ)J");
        if (!g_mid_createPresenter_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: createPresenter_call sig=(JJJJ)J"); }
        g_mid_flutterTextureId_call = env->GetStaticMethodID(g_bridgeClass, "flutterTextureId_call", "(JJ)J");
        if (!g_mid_flutterTextureId_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: flutterTextureId_call sig=(JJ)J"); }
        g_mid_acquireFrame_call = env->GetStaticMethodID(g_bridgeClass, "acquireFrame_call", "(JJJJ)V");
        if (!g_mid_acquireFrame_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: acquireFrame_call sig=(JJJJ)V"); }
        g_mid_acquireFrameSync_call = env->GetStaticMethodID(g_bridgeClass, "acquireFrameSync_call", "(JJ)J");
        if (!g_mid_acquireFrameSync_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: acquireFrameSync_call sig=(JJ)J"); }
        g_mid_presentFrame_call = env->GetStaticMethodID(g_bridgeClass, "presentFrame_call", "(JJ)V");
        if (!g_mid_presentFrame_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: presentFrame_call sig=(JJ)V"); }
        g_mid_presenterFormat_call = env->GetStaticMethodID(g_bridgeClass, "presenterFormat_call", "(JJ)J");
        if (!g_mid_presenterFormat_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: presenterFormat_call sig=(JJ)J"); }
        g_mid_presenterUsesGpuPath_call = env->GetStaticMethodID(g_bridgeClass, "presenterUsesGpuPath_call", "(JJ)Z");
        if (!g_mid_presenterUsesGpuPath_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: presenterUsesGpuPath_call sig=(JJ)Z"); }
        g_mid_resizePresenter_call = env->GetStaticMethodID(g_bridgeClass, "resizePresenter_call", "(JJJJ)V");
        if (!g_mid_resizePresenter_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: resizePresenter_call sig=(JJJJ)V"); }
        g_mid_presenterSetSurfaceSize_call = env->GetStaticMethodID(g_bridgeClass, "presenterSetSurfaceSize_call", "(JJJJ)V");
        if (!g_mid_presenterSetSurfaceSize_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: presenterSetSurfaceSize_call sig=(JJJJ)V"); }
        g_mid_requestMaxRefreshRate_call = env->GetStaticMethodID(g_bridgeClass, "requestMaxRefreshRate_call", "(J)D");
        if (!g_mid_requestMaxRefreshRate_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: requestMaxRefreshRate_call sig=(J)D"); }
        g_mid_destroyPresenter_call = env->GetStaticMethodID(g_bridgeClass, "destroyPresenter_call", "(JJJJ)V");
        if (!g_mid_destroyPresenter_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: destroyPresenter_call sig=(JJJJ)V"); }
    }

}

// ── postXxxToPort helpers for @nitroNativeAsync ──
JNIEXPORT void JNICALL Java_nitro_nitro_1webgpu_1present_1module_NitroWebgpuPresentJniBridge_postNullToPort(JNIEnv*, jclass, jlong dartPort) {
    Dart_CObject obj;
    obj.type = Dart_CObject_kNull;
    Dart_PostCObject_DL((Dart_Port)dartPort, &obj);
}

JNIEXPORT void JNICALL Java_nitro_nitro_1webgpu_1present_1module_NitroWebgpuPresentJniBridge_postInt64ToPort(JNIEnv*, jclass, jlong dartPort, jlong value) {
    Dart_CObject obj;
    obj.type = Dart_CObject_kInt64;
    obj.value.as_int64 = (int64_t)value;
    Dart_PostCObject_DL((Dart_Port)dartPort, &obj);
}

JNIEXPORT void JNICALL Java_nitro_nitro_1webgpu_1present_1module_NitroWebgpuPresentJniBridge_postDoubleToPort(JNIEnv*, jclass, jlong dartPort, jdouble value) {
    Dart_CObject obj;
    obj.type = Dart_CObject_kDouble;
    obj.value.as_double = (double)value;
    Dart_PostCObject_DL((Dart_Port)dartPort, &obj);
}

JNIEXPORT void JNICALL Java_nitro_nitro_1webgpu_1present_1module_NitroWebgpuPresentJniBridge_postBoolToPort(JNIEnv*, jclass, jlong dartPort, jboolean value) {
    Dart_CObject obj;
    obj.type = Dart_CObject_kBool;
    obj.value.as_bool = (bool)value;
    Dart_PostCObject_DL((Dart_Port)dartPort, &obj);
}

JNIEXPORT void JNICALL Java_nitro_nitro_1webgpu_1present_1module_NitroWebgpuPresentJniBridge_postStringToPort(JNIEnv* env, jclass, jlong dartPort, jstring value) {
    Dart_CObject obj;
    if (value == nullptr) {
        obj.type = Dart_CObject_kNull;
        Dart_PostCObject_DL((Dart_Port)dartPort, &obj);
        return;
    }
    const char* cStr = env->GetStringUTFChars(value, nullptr);
    if (cStr == nullptr) {
        obj.type = Dart_CObject_kNull;
        Dart_PostCObject_DL((Dart_Port)dartPort, &obj);
        return;
    }
    obj.type = Dart_CObject_kString;
    obj.value.as_string = const_cast<char*>(cStr);
    Dart_PostCObject_DL((Dart_Port)dartPort, &obj);
    env->ReleaseStringUTFChars(value, cStr);
}

JNIEXPORT void JNICALL Java_nitro_nitro_1webgpu_1present_1module_NitroWebgpuPresentJniBridge_postOptInt64ToPort(JNIEnv*, jclass, jlong dartPort, jlong value, jboolean hasValue) {
    uint8_t* buf = (uint8_t*)malloc(9);
    buf[0] = hasValue ? 1 : 0;
    if (hasValue) { memcpy(buf + 1, &value, 8); }
    Dart_CObject obj;
    obj.type = Dart_CObject_kInt64;
    obj.value.as_int64 = (int64_t)(uintptr_t)buf;
    Dart_PostCObject_DL((Dart_Port)dartPort, &obj);
}

JNIEXPORT void JNICALL Java_nitro_nitro_1webgpu_1present_1module_NitroWebgpuPresentJniBridge_postOptFloat64ToPort(JNIEnv*, jclass, jlong dartPort, jdouble value, jboolean hasValue) {
    uint8_t* buf = (uint8_t*)malloc(9);
    buf[0] = hasValue ? 1 : 0;
    if (hasValue) { memcpy(buf + 1, &value, 8); }
    Dart_CObject obj;
    obj.type = Dart_CObject_kInt64;
    obj.value.as_int64 = (int64_t)(uintptr_t)buf;
    Dart_PostCObject_DL((Dart_Port)dartPort, &obj);
}

JNIEXPORT void JNICALL Java_nitro_nitro_1webgpu_1present_1module_NitroWebgpuPresentJniBridge_postOptBoolToPort(JNIEnv*, jclass, jlong dartPort, jboolean value, jboolean hasValue) {
    uint8_t* buf = (uint8_t*)malloc(2);
    buf[0] = hasValue ? 1 : 0;
    buf[1] = value ? 1 : 0;
    Dart_CObject obj;
    obj.type = Dart_CObject_kInt64;
    obj.value.as_int64 = (int64_t)(uintptr_t)buf;
    Dart_PostCObject_DL((Dart_Port)dartPort, &obj);
}

JNIEXPORT void JNICALL Java_nitro_nitro_1webgpu_1present_1module_NitroWebgpuPresentJniBridge_postBytesToPort(JNIEnv* env, jclass, jlong dartPort, jbyteArray value) {
    Dart_CObject obj;
    obj.type = Dart_CObject_kInt64;
    if (value == nullptr) {
        obj.value.as_int64 = 0;
    } else {
        jsize len = env->GetArrayLength(value);
        uint8_t* buf = (uint8_t*)malloc(len);
        env->GetByteArrayRegion(value, 0, len, (jbyte*)buf);
        obj.value.as_int64 = (int64_t)(uintptr_t)buf;
    }
    Dart_PostCObject_DL((Dart_Port)dartPort, &obj);
}

JNIEXPORT void JNICALL Java_nitro_nitro_1webgpu_1present_1module_NitroWebgpuPresentJniBridge_reportNativeAsyncError(JNIEnv* env, jclass, jlong errPtr, jstring name, jstring message) {
    NitroError* err = (NitroError*)(uintptr_t)errPtr;
    if (err == nullptr) { return; }
    err->hasError = 1;
    if (name != nullptr) {
        const char* cName = env->GetStringUTFChars(name, nullptr);
        err->name = strdup(cName);
        env->ReleaseStringUTFChars(name, cName);
    } else {
        err->name = strdup("NativeException");
    }
    if (message != nullptr) {
        const char* cMsg = env->GetStringUTFChars(message, nullptr);
        err->message = strdup(cMsg);
        env->ReleaseStringUTFChars(message, cMsg);
    } else {
        err->message = strdup("An unknown native exception occurred.");
    }
    err->code = nullptr;
    err->stackTrace = nullptr;
}

} // extern "C"
#elif __APPLE__
extern "C" {
extern int64_t _nitro_webgpu_present_call_createPresenter(int64_t deviceAddress, int64_t widthPx, int64_t heightPx);
int64_t nitro_webgpu_present_create_presenter(int64_t instanceId, int64_t deviceAddress, int64_t widthPx, int64_t heightPx, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }
#ifdef __OBJC__
    @try {
        return _nitro_webgpu_present_call_createPresenter(deviceAddress, widthPx, heightPx);
    } @catch (NSException* e) {
        if (_nitro_err) {
            // sync: write exception to out-param error slot.
            _nitro_err->hasError = 1;
            _nitro_err->name    = strdup([e.name UTF8String]);
            _nitro_err->message = strdup([e.reason UTF8String]);
            _nitro_err->code = nullptr;
            _nitro_err->stackTrace = nullptr;
        } else {
            // async: _nitro_err is null — route exception to TLS slot.
            nitro_report_error([e.name UTF8String], [e.reason UTF8String], nullptr, nullptr);
        }
        return 0;
    }
#else
    return _nitro_webgpu_present_call_createPresenter(deviceAddress, widthPx, heightPx);
#endif
}

extern int64_t _nitro_webgpu_present_call_flutterTextureId(int64_t token);
int64_t nitro_webgpu_present_flutter_texture_id(int64_t instanceId, int64_t token, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }
#ifdef __OBJC__
    @try {
        return _nitro_webgpu_present_call_flutterTextureId(token);
    } @catch (NSException* e) {
        if (_nitro_err) {
            // sync: write exception to out-param error slot.
            _nitro_err->hasError = 1;
            _nitro_err->name    = strdup([e.name UTF8String]);
            _nitro_err->message = strdup([e.reason UTF8String]);
            _nitro_err->code = nullptr;
            _nitro_err->stackTrace = nullptr;
        } else {
            // async: _nitro_err is null — route exception to TLS slot.
            nitro_report_error([e.name UTF8String], [e.reason UTF8String], nullptr, nullptr);
        }
        return 0;
    }
#else
    return _nitro_webgpu_present_call_flutterTextureId(token);
#endif
}

extern void _nitro_webgpu_present_call_acquireFrame(int64_t token, int64_t err_ptr, int64_t dart_port);
void nitro_webgpu_present_acquire_frame(int64_t instanceId, int64_t token, NitroError* _nitro_err, int64_t dart_port) {
    nitro_webgpu_present_clear_error();
    _nitro_webgpu_present_call_acquireFrame(token, (int64_t)(uintptr_t)_nitro_err, dart_port);
}

extern int64_t _nitro_webgpu_present_call_acquireFrameSync(int64_t token);
int64_t nitro_webgpu_present_acquire_frame_sync(int64_t instanceId, int64_t token, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }
#ifdef __OBJC__
    @try {
        return _nitro_webgpu_present_call_acquireFrameSync(token);
    } @catch (NSException* e) {
        if (_nitro_err) {
            // sync: write exception to out-param error slot.
            _nitro_err->hasError = 1;
            _nitro_err->name    = strdup([e.name UTF8String]);
            _nitro_err->message = strdup([e.reason UTF8String]);
            _nitro_err->code = nullptr;
            _nitro_err->stackTrace = nullptr;
        } else {
            // async: _nitro_err is null — route exception to TLS slot.
            nitro_report_error([e.name UTF8String], [e.reason UTF8String], nullptr, nullptr);
        }
        return 0;
    }
#else
    return _nitro_webgpu_present_call_acquireFrameSync(token);
#endif
}

extern void _nitro_webgpu_present_call_presentFrame(int64_t token);
void nitro_webgpu_present_present_frame(int64_t instanceId, int64_t token, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }
#ifdef __OBJC__
    @try {
        _nitro_webgpu_present_call_presentFrame(token);
    } @catch (NSException* e) {
        if (_nitro_err) {
            // sync: write exception to out-param error slot.
            _nitro_err->hasError = 1;
            _nitro_err->name    = strdup([e.name UTF8String]);
            _nitro_err->message = strdup([e.reason UTF8String]);
            _nitro_err->code = nullptr;
            _nitro_err->stackTrace = nullptr;
        } else {
            // async: _nitro_err is null — route exception to TLS slot.
            nitro_report_error([e.name UTF8String], [e.reason UTF8String], nullptr, nullptr);
        }
    }
#else
    _nitro_webgpu_present_call_presentFrame(token);
#endif
}

extern int64_t _nitro_webgpu_present_call_presenterFormat(int64_t token);
int64_t nitro_webgpu_present_presenter_format(int64_t instanceId, int64_t token, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }
#ifdef __OBJC__
    @try {
        return _nitro_webgpu_present_call_presenterFormat(token);
    } @catch (NSException* e) {
        if (_nitro_err) {
            // sync: write exception to out-param error slot.
            _nitro_err->hasError = 1;
            _nitro_err->name    = strdup([e.name UTF8String]);
            _nitro_err->message = strdup([e.reason UTF8String]);
            _nitro_err->code = nullptr;
            _nitro_err->stackTrace = nullptr;
        } else {
            // async: _nitro_err is null — route exception to TLS slot.
            nitro_report_error([e.name UTF8String], [e.reason UTF8String], nullptr, nullptr);
        }
        return 0;
    }
#else
    return _nitro_webgpu_present_call_presenterFormat(token);
#endif
}

extern int8_t _nitro_webgpu_present_call_presenterUsesGpuPath(int64_t token);
int8_t nitro_webgpu_present_presenter_uses_gpu_path(int64_t instanceId, int64_t token, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }
#ifdef __OBJC__
    @try {
        return _nitro_webgpu_present_call_presenterUsesGpuPath(token);
    } @catch (NSException* e) {
        if (_nitro_err) {
            // sync: write exception to out-param error slot.
            _nitro_err->hasError = 1;
            _nitro_err->name    = strdup([e.name UTF8String]);
            _nitro_err->message = strdup([e.reason UTF8String]);
            _nitro_err->code = nullptr;
            _nitro_err->stackTrace = nullptr;
        } else {
            // async: _nitro_err is null — route exception to TLS slot.
            nitro_report_error([e.name UTF8String], [e.reason UTF8String], nullptr, nullptr);
        }
        return false;
    }
#else
    return _nitro_webgpu_present_call_presenterUsesGpuPath(token);
#endif
}

extern void _nitro_webgpu_present_call_resizePresenter(int64_t token, int64_t widthPx, int64_t heightPx);
void nitro_webgpu_present_resize_presenter(int64_t instanceId, int64_t token, int64_t widthPx, int64_t heightPx, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }
#ifdef __OBJC__
    @try {
        _nitro_webgpu_present_call_resizePresenter(token, widthPx, heightPx);
    } @catch (NSException* e) {
        if (_nitro_err) {
            // sync: write exception to out-param error slot.
            _nitro_err->hasError = 1;
            _nitro_err->name    = strdup([e.name UTF8String]);
            _nitro_err->message = strdup([e.reason UTF8String]);
            _nitro_err->code = nullptr;
            _nitro_err->stackTrace = nullptr;
        } else {
            // async: _nitro_err is null — route exception to TLS slot.
            nitro_report_error([e.name UTF8String], [e.reason UTF8String], nullptr, nullptr);
        }
    }
#else
    _nitro_webgpu_present_call_resizePresenter(token, widthPx, heightPx);
#endif
}

extern void _nitro_webgpu_present_call_presenterSetSurfaceSize(int64_t token, int64_t widthPx, int64_t heightPx);
void nitro_webgpu_present_presenter_set_surface_size(int64_t instanceId, int64_t token, int64_t widthPx, int64_t heightPx, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }
#ifdef __OBJC__
    @try {
        _nitro_webgpu_present_call_presenterSetSurfaceSize(token, widthPx, heightPx);
    } @catch (NSException* e) {
        if (_nitro_err) {
            // sync: write exception to out-param error slot.
            _nitro_err->hasError = 1;
            _nitro_err->name    = strdup([e.name UTF8String]);
            _nitro_err->message = strdup([e.reason UTF8String]);
            _nitro_err->code = nullptr;
            _nitro_err->stackTrace = nullptr;
        } else {
            // async: _nitro_err is null — route exception to TLS slot.
            nitro_report_error([e.name UTF8String], [e.reason UTF8String], nullptr, nullptr);
        }
    }
#else
    _nitro_webgpu_present_call_presenterSetSurfaceSize(token, widthPx, heightPx);
#endif
}

extern double _nitro_webgpu_present_call_requestMaxRefreshRate(void);
double nitro_webgpu_present_request_max_refresh_rate(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }
#ifdef __OBJC__
    @try {
        return _nitro_webgpu_present_call_requestMaxRefreshRate();
    } @catch (NSException* e) {
        if (_nitro_err) {
            // sync: write exception to out-param error slot.
            _nitro_err->hasError = 1;
            _nitro_err->name    = strdup([e.name UTF8String]);
            _nitro_err->message = strdup([e.reason UTF8String]);
            _nitro_err->code = nullptr;
            _nitro_err->stackTrace = nullptr;
        } else {
            // async: _nitro_err is null — route exception to TLS slot.
            nitro_report_error([e.name UTF8String], [e.reason UTF8String], nullptr, nullptr);
        }
        return 0.0;
    }
#else
    return _nitro_webgpu_present_call_requestMaxRefreshRate();
#endif
}

extern void _nitro_webgpu_present_call_destroyPresenter(int64_t token, int64_t err_ptr, int64_t dart_port);
void nitro_webgpu_present_destroy_presenter(int64_t instanceId, int64_t token, NitroError* _nitro_err, int64_t dart_port) {
    nitro_webgpu_present_clear_error();
    _nitro_webgpu_present_call_destroyPresenter(token, (int64_t)(uintptr_t)_nitro_err, dart_port);
}

static int64_t nitro_webgpu_present_g_next_instance_id = 0;
NITRO_EXPORT int64_t nitro_webgpu_present_create_instance(const char* key) { (void)key; return nitro_webgpu_present_g_next_instance_id++; }
NITRO_EXPORT void nitro_webgpu_present_destroy_instance(int64_t instanceId) { (void)instanceId; }
NITRO_EXPORT void nitro_webgpu_present_nitro_free(void* ptr) { if (ptr) { free(ptr); } }
NITRO_EXPORT void* nitro_webgpu_present_nitro_alloc(size_t size) { return malloc(size); }

} // extern "C"
#elif defined(_WIN32) || defined(__linux__)  // Windows/Linux: NativeImpl.cpp — direct C++ dispatch
#include "nitro_webgpu_present.native.g.h"

static void _nitro_desktop_err(NitroError* _out, const char* _name, const char* _message) {
    nitro_report_error(_name, _message, nullptr, nullptr);
    if (_out) {
        _out->hasError = 1;
        _out->name = _name ? strdup(_name) : nullptr;
        _out->message = _message ? strdup(_message) : nullptr;
        _out->code = nullptr;
        _out->stackTrace = nullptr;
    }
}

static HybridNitroWebgpuPresent* g_impl = nullptr;
static int64_t g_next_instance_id = 0;

extern "C" {
void nitro_webgpu_present_register_impl(HybridNitroWebgpuPresent* impl) { g_impl = impl; }
HybridNitroWebgpuPresent* nitro_webgpu_present_get_impl() { return g_impl; }
NITRO_EXPORT int64_t nitro_webgpu_present_create_instance(const char* key) { (void)key; return g_next_instance_id++; }
NITRO_EXPORT void nitro_webgpu_present_destroy_instance(int64_t instanceId) { (void)instanceId; }
NITRO_EXPORT void nitro_webgpu_present_nitro_free(void* ptr) { if (ptr) { free(ptr); } }
NITRO_EXPORT void* nitro_webgpu_present_nitro_alloc(size_t size) { return malloc(size); }

int64_t nitro_webgpu_present_create_presenter(int64_t instanceId, int64_t deviceAddress, int64_t widthPx, int64_t heightPx, NitroError* _nitro_err) {
    nitro_webgpu_present_clear_error();
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    if (!g_impl) { _nitro_desktop_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_webgpu_present_register_impl() first."); return 0; }
    try {
        return g_impl->createPresenter(deviceAddress, widthPx, heightPx);
    } catch (const std::exception& e) {
        _nitro_desktop_err(_nitro_err, "CppException", e.what());
        return 0;
    } catch (...) {
        _nitro_desktop_err(_nitro_err, "CppException", "Unknown C++ exception");
        return 0;
    }
}

int64_t nitro_webgpu_present_flutter_texture_id(int64_t instanceId, int64_t token, NitroError* _nitro_err) {
    nitro_webgpu_present_clear_error();
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    if (!g_impl) { _nitro_desktop_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_webgpu_present_register_impl() first."); return 0; }
    try {
        return g_impl->flutterTextureId(token);
    } catch (const std::exception& e) {
        _nitro_desktop_err(_nitro_err, "CppException", e.what());
        return 0;
    } catch (...) {
        _nitro_desktop_err(_nitro_err, "CppException", "Unknown C++ exception");
        return 0;
    }
}

void nitro_webgpu_present_acquire_frame(int64_t instanceId, int64_t token, NitroError* _nitro_err, int64_t dart_port) {
    if (_nitro_err) { _nitro_err->hasError = 0; }
    if (!g_impl) {
        _nitro_desktop_err(_nitro_err, "NotInitialized", "No C++ implementation registered.");
        Dart_CObject _err = { Dart_CObject_kNull };
        Dart_PostCObject_DL(dart_port, &_err);
        return;
    }
    try {
        g_impl->acquireFrame(token, _nitro_err, dart_port);
    } catch (const std::exception& e) {
        _nitro_desktop_err(_nitro_err, "CppException", e.what());
        Dart_CObject _err = { Dart_CObject_kNull };
        Dart_PostCObject_DL(dart_port, &_err);
    } catch (...) {
        _nitro_desktop_err(_nitro_err, "CppException", "Unknown C++ exception");
        Dart_CObject _err = { Dart_CObject_kNull };
        Dart_PostCObject_DL(dart_port, &_err);
    }
}

int64_t nitro_webgpu_present_acquire_frame_sync(int64_t instanceId, int64_t token, NitroError* _nitro_err) {
    nitro_webgpu_present_clear_error();
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    if (!g_impl) { _nitro_desktop_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_webgpu_present_register_impl() first."); return 0; }
    try {
        return g_impl->acquireFrameSync(token);
    } catch (const std::exception& e) {
        _nitro_desktop_err(_nitro_err, "CppException", e.what());
        return 0;
    } catch (...) {
        _nitro_desktop_err(_nitro_err, "CppException", "Unknown C++ exception");
        return 0;
    }
}

void nitro_webgpu_present_present_frame(int64_t instanceId, int64_t token, NitroError* _nitro_err) {
    nitro_webgpu_present_clear_error();
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    if (!g_impl) { _nitro_desktop_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_webgpu_present_register_impl() first."); return; }
    try {
        g_impl->presentFrame(token);
    } catch (const std::exception& e) {
        _nitro_desktop_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_desktop_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

int64_t nitro_webgpu_present_presenter_format(int64_t instanceId, int64_t token, NitroError* _nitro_err) {
    nitro_webgpu_present_clear_error();
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    if (!g_impl) { _nitro_desktop_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_webgpu_present_register_impl() first."); return 0; }
    try {
        return g_impl->presenterFormat(token);
    } catch (const std::exception& e) {
        _nitro_desktop_err(_nitro_err, "CppException", e.what());
        return 0;
    } catch (...) {
        _nitro_desktop_err(_nitro_err, "CppException", "Unknown C++ exception");
        return 0;
    }
}

int8_t nitro_webgpu_present_presenter_uses_gpu_path(int64_t instanceId, int64_t token, NitroError* _nitro_err) {
    nitro_webgpu_present_clear_error();
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    if (!g_impl) { _nitro_desktop_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_webgpu_present_register_impl() first."); return false; }
    try {
        return g_impl->presenterUsesGpuPath(token);
    } catch (const std::exception& e) {
        _nitro_desktop_err(_nitro_err, "CppException", e.what());
        return false;
    } catch (...) {
        _nitro_desktop_err(_nitro_err, "CppException", "Unknown C++ exception");
        return false;
    }
}

void nitro_webgpu_present_resize_presenter(int64_t instanceId, int64_t token, int64_t widthPx, int64_t heightPx, NitroError* _nitro_err) {
    nitro_webgpu_present_clear_error();
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    if (!g_impl) { _nitro_desktop_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_webgpu_present_register_impl() first."); return; }
    try {
        g_impl->resizePresenter(token, widthPx, heightPx);
    } catch (const std::exception& e) {
        _nitro_desktop_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_desktop_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_webgpu_present_presenter_set_surface_size(int64_t instanceId, int64_t token, int64_t widthPx, int64_t heightPx, NitroError* _nitro_err) {
    nitro_webgpu_present_clear_error();
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    if (!g_impl) { _nitro_desktop_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_webgpu_present_register_impl() first."); return; }
    try {
        g_impl->presenterSetSurfaceSize(token, widthPx, heightPx);
    } catch (const std::exception& e) {
        _nitro_desktop_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_desktop_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

double nitro_webgpu_present_request_max_refresh_rate(int64_t instanceId, NitroError* _nitro_err) {
    nitro_webgpu_present_clear_error();
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    if (!g_impl) { _nitro_desktop_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_webgpu_present_register_impl() first."); return 0.0; }
    try {
        return g_impl->requestMaxRefreshRate();
    } catch (const std::exception& e) {
        _nitro_desktop_err(_nitro_err, "CppException", e.what());
        return 0.0;
    } catch (...) {
        _nitro_desktop_err(_nitro_err, "CppException", "Unknown C++ exception");
        return 0.0;
    }
}

void nitro_webgpu_present_destroy_presenter(int64_t instanceId, int64_t token, NitroError* _nitro_err, int64_t dart_port) {
    if (_nitro_err) { _nitro_err->hasError = 0; }
    if (!g_impl) {
        _nitro_desktop_err(_nitro_err, "NotInitialized", "No C++ implementation registered.");
        Dart_CObject _err = { Dart_CObject_kNull };
        Dart_PostCObject_DL(dart_port, &_err);
        return;
    }
    try {
        g_impl->destroyPresenter(token, _nitro_err, dart_port);
    } catch (const std::exception& e) {
        _nitro_desktop_err(_nitro_err, "CppException", e.what());
        Dart_CObject _err = { Dart_CObject_kNull };
        Dart_PostCObject_DL(dart_port, &_err);
    } catch (...) {
        _nitro_desktop_err(_nitro_err, "CppException", "Unknown C++ exception");
        Dart_CObject _err = { Dart_CObject_kNull };
        Dart_PostCObject_DL(dart_port, &_err);
    }
}

} // extern "C"
#endif
