// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.5.12
// Generated from: nitro_webgpu.native.dart
import Foundation
import Combine

// Shared types (structs, NitroRecordWriter, NitroRecordReader) are declared
// in the Swift module's .bridge.g.swift — compiled into the same module.
// Do NOT redeclare them here.
//
// No @_cdecl stubs are generated: the C++ bridge (.bridge.g.mm) calls
// nitro_webgpu_xxx C functions directly — Swift @_cdecl stubs are unused
// and would conflict with the Swift module's exported symbols.

// --- @HybridRecord binary extensions (generated by Nitrogen) ---

public struct GpuInstanceOptions: NitroEncodable {
  public var backends: Int64

  public init(backends: Int64) {
    self.backends = backends
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuInstanceOptions {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuInstanceOptions {
    return GpuInstanceOptions(
      backends: r.readInt(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(backends)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuRequestAdapterOptions: NitroEncodable {
  public var powerPreference: Int64
  public var forceFallbackAdapter: Bool

  public init(powerPreference: Int64, forceFallbackAdapter: Bool) {
    self.powerPreference = powerPreference
    self.forceFallbackAdapter = forceFallbackAdapter
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuRequestAdapterOptions {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuRequestAdapterOptions {
    return GpuRequestAdapterOptions(
      powerPreference: r.readInt(),
      forceFallbackAdapter: r.readBool(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(powerPreference)
    writer.writeBool(forceFallbackAdapter)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuAdapterInfo: NitroEncodable {
  public var vendor: String
  public var architecture: String
  public var device: String
  public var description: String
  public var backendType: Int64
  public var adapterType: Int64

  public init(vendor: String, architecture: String, device: String, description: String, backendType: Int64, adapterType: Int64) {
    self.vendor = vendor
    self.architecture = architecture
    self.device = device
    self.description = description
    self.backendType = backendType
    self.adapterType = adapterType
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuAdapterInfo {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuAdapterInfo {
    return GpuAdapterInfo(
      vendor: r.readString(),
      architecture: r.readString(),
      device: r.readString(),
      description: r.readString(),
      backendType: r.readInt(),
      adapterType: r.readInt(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(vendor)
    writer.writeString(architecture)
    writer.writeString(device)
    writer.writeString(description)
    writer.writeInt(backendType)
    writer.writeInt(adapterType)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuLimits: NitroEncodable {
  public var maxTextureDimension1D: Int64
  public var maxTextureDimension2D: Int64
  public var maxTextureDimension3D: Int64
  public var maxTextureArrayLayers: Int64
  public var maxBindGroups: Int64
  public var maxBindingsPerBindGroup: Int64
  public var maxUniformBufferBindingSize: Int64
  public var maxStorageBufferBindingSize: Int64
  public var minUniformBufferOffsetAlignment: Int64
  public var minStorageBufferOffsetAlignment: Int64
  public var maxBufferSize: Int64
  public var maxComputeWorkgroupStorageSize: Int64
  public var maxComputeInvocationsPerWorkgroup: Int64
  public var maxComputeWorkgroupSizeX: Int64
  public var maxComputeWorkgroupSizeY: Int64
  public var maxComputeWorkgroupSizeZ: Int64

  public init(maxTextureDimension1D: Int64, maxTextureDimension2D: Int64, maxTextureDimension3D: Int64, maxTextureArrayLayers: Int64, maxBindGroups: Int64, maxBindingsPerBindGroup: Int64, maxUniformBufferBindingSize: Int64, maxStorageBufferBindingSize: Int64, minUniformBufferOffsetAlignment: Int64, minStorageBufferOffsetAlignment: Int64, maxBufferSize: Int64, maxComputeWorkgroupStorageSize: Int64, maxComputeInvocationsPerWorkgroup: Int64, maxComputeWorkgroupSizeX: Int64, maxComputeWorkgroupSizeY: Int64, maxComputeWorkgroupSizeZ: Int64) {
    self.maxTextureDimension1D = maxTextureDimension1D
    self.maxTextureDimension2D = maxTextureDimension2D
    self.maxTextureDimension3D = maxTextureDimension3D
    self.maxTextureArrayLayers = maxTextureArrayLayers
    self.maxBindGroups = maxBindGroups
    self.maxBindingsPerBindGroup = maxBindingsPerBindGroup
    self.maxUniformBufferBindingSize = maxUniformBufferBindingSize
    self.maxStorageBufferBindingSize = maxStorageBufferBindingSize
    self.minUniformBufferOffsetAlignment = minUniformBufferOffsetAlignment
    self.minStorageBufferOffsetAlignment = minStorageBufferOffsetAlignment
    self.maxBufferSize = maxBufferSize
    self.maxComputeWorkgroupStorageSize = maxComputeWorkgroupStorageSize
    self.maxComputeInvocationsPerWorkgroup = maxComputeInvocationsPerWorkgroup
    self.maxComputeWorkgroupSizeX = maxComputeWorkgroupSizeX
    self.maxComputeWorkgroupSizeY = maxComputeWorkgroupSizeY
    self.maxComputeWorkgroupSizeZ = maxComputeWorkgroupSizeZ
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuLimits {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuLimits {
    return GpuLimits(
      maxTextureDimension1D: r.readInt(),
      maxTextureDimension2D: r.readInt(),
      maxTextureDimension3D: r.readInt(),
      maxTextureArrayLayers: r.readInt(),
      maxBindGroups: r.readInt(),
      maxBindingsPerBindGroup: r.readInt(),
      maxUniformBufferBindingSize: r.readInt(),
      maxStorageBufferBindingSize: r.readInt(),
      minUniformBufferOffsetAlignment: r.readInt(),
      minStorageBufferOffsetAlignment: r.readInt(),
      maxBufferSize: r.readInt(),
      maxComputeWorkgroupStorageSize: r.readInt(),
      maxComputeInvocationsPerWorkgroup: r.readInt(),
      maxComputeWorkgroupSizeX: r.readInt(),
      maxComputeWorkgroupSizeY: r.readInt(),
      maxComputeWorkgroupSizeZ: r.readInt(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(maxTextureDimension1D)
    writer.writeInt(maxTextureDimension2D)
    writer.writeInt(maxTextureDimension3D)
    writer.writeInt(maxTextureArrayLayers)
    writer.writeInt(maxBindGroups)
    writer.writeInt(maxBindingsPerBindGroup)
    writer.writeInt(maxUniformBufferBindingSize)
    writer.writeInt(maxStorageBufferBindingSize)
    writer.writeInt(minUniformBufferOffsetAlignment)
    writer.writeInt(minStorageBufferOffsetAlignment)
    writer.writeInt(maxBufferSize)
    writer.writeInt(maxComputeWorkgroupStorageSize)
    writer.writeInt(maxComputeInvocationsPerWorkgroup)
    writer.writeInt(maxComputeWorkgroupSizeX)
    writer.writeInt(maxComputeWorkgroupSizeY)
    writer.writeInt(maxComputeWorkgroupSizeZ)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuDeviceDescriptor: NitroEncodable {
  public var label: String
  public var requireTimestampQueries: Bool
  public var requiredLimits: GpuRequiredLimits?

  public init(label: String, requireTimestampQueries: Bool, requiredLimits: GpuRequiredLimits?) {
    self.label = label
    self.requireTimestampQueries = requireTimestampQueries
    self.requiredLimits = requiredLimits
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuDeviceDescriptor {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuDeviceDescriptor {
    return GpuDeviceDescriptor(
      label: r.readString(),
      requireTimestampQueries: r.readBool(),
      requiredLimits: r.readNullTag() ? nil : GpuRequiredLimits.fromReader(r),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(label)
    writer.writeBool(requireTimestampQueries)
    writer.writeNullTag(requiredLimits == nil)
    if let val = requiredLimits { val.writeFields(writer) }
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuComputePassDescriptor: NitroEncodable {
  public var label: String
  public var timestampQuerySetAddress: Int64
  public var timestampBeginIndex: Int64
  public var timestampEndIndex: Int64

  public init(label: String, timestampQuerySetAddress: Int64, timestampBeginIndex: Int64, timestampEndIndex: Int64) {
    self.label = label
    self.timestampQuerySetAddress = timestampQuerySetAddress
    self.timestampBeginIndex = timestampBeginIndex
    self.timestampEndIndex = timestampEndIndex
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuComputePassDescriptor {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuComputePassDescriptor {
    return GpuComputePassDescriptor(
      label: r.readString(),
      timestampQuerySetAddress: r.readInt(),
      timestampBeginIndex: r.readInt(),
      timestampEndIndex: r.readInt(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(label)
    writer.writeInt(timestampQuerySetAddress)
    writer.writeInt(timestampBeginIndex)
    writer.writeInt(timestampEndIndex)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuError: NitroEncodable {
  public var type: Int64
  public var message: String

  public init(type: Int64, message: String) {
    self.type = type
    self.message = message
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuError {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuError {
    return GpuError(
      type: r.readInt(),
      message: r.readString(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(type)
    writer.writeString(message)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuUncapturedError: NitroEncodable {
  public var deviceAddress: Int64
  public var type: Int64
  public var message: String

  public init(deviceAddress: Int64, type: Int64, message: String) {
    self.deviceAddress = deviceAddress
    self.type = type
    self.message = message
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuUncapturedError {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuUncapturedError {
    return GpuUncapturedError(
      deviceAddress: r.readInt(),
      type: r.readInt(),
      message: r.readString(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(deviceAddress)
    writer.writeInt(type)
    writer.writeString(message)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuDeviceLost: NitroEncodable {
  public var deviceAddress: Int64
  public var reason: Int64
  public var message: String

  public init(deviceAddress: Int64, reason: Int64, message: String) {
    self.deviceAddress = deviceAddress
    self.reason = reason
    self.message = message
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuDeviceLost {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuDeviceLost {
    return GpuDeviceLost(
      deviceAddress: r.readInt(),
      reason: r.readInt(),
      message: r.readString(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(deviceAddress)
    writer.writeInt(reason)
    writer.writeString(message)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuBufferDescriptor: NitroEncodable {
  public var label: String
  public var size: Int64
  public var usage: Int64
  public var mappedAtCreation: Bool

  public init(label: String, size: Int64, usage: Int64, mappedAtCreation: Bool) {
    self.label = label
    self.size = size
    self.usage = usage
    self.mappedAtCreation = mappedAtCreation
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuBufferDescriptor {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuBufferDescriptor {
    return GpuBufferDescriptor(
      label: r.readString(),
      size: r.readInt(),
      usage: r.readInt(),
      mappedAtCreation: r.readBool(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(label)
    writer.writeInt(size)
    writer.writeInt(usage)
    writer.writeBool(mappedAtCreation)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuBindGroupEntry: NitroEncodable {
  public var binding: Int64
  public var bufferAddress: Int64
  public var offset: Int64
  public var size: Int64
  public var samplerAddress: Int64
  public var textureViewAddress: Int64

  public init(binding: Int64, bufferAddress: Int64, offset: Int64, size: Int64, samplerAddress: Int64, textureViewAddress: Int64) {
    self.binding = binding
    self.bufferAddress = bufferAddress
    self.offset = offset
    self.size = size
    self.samplerAddress = samplerAddress
    self.textureViewAddress = textureViewAddress
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuBindGroupEntry {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuBindGroupEntry {
    return GpuBindGroupEntry(
      binding: r.readInt(),
      bufferAddress: r.readInt(),
      offset: r.readInt(),
      size: r.readInt(),
      samplerAddress: r.readInt(),
      textureViewAddress: r.readInt(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(binding)
    writer.writeInt(bufferAddress)
    writer.writeInt(offset)
    writer.writeInt(size)
    writer.writeInt(samplerAddress)
    writer.writeInt(textureViewAddress)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuSamplerDescriptor: NitroEncodable {
  public var label: String
  public var magFilter: Int64
  public var minFilter: Int64
  public var mipmapFilter: Int64
  public var addressModeU: Int64
  public var addressModeV: Int64
  public var addressModeW: Int64

  public init(label: String, magFilter: Int64, minFilter: Int64, mipmapFilter: Int64, addressModeU: Int64, addressModeV: Int64, addressModeW: Int64) {
    self.label = label
    self.magFilter = magFilter
    self.minFilter = minFilter
    self.mipmapFilter = mipmapFilter
    self.addressModeU = addressModeU
    self.addressModeV = addressModeV
    self.addressModeW = addressModeW
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuSamplerDescriptor {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuSamplerDescriptor {
    return GpuSamplerDescriptor(
      label: r.readString(),
      magFilter: r.readInt(),
      minFilter: r.readInt(),
      mipmapFilter: r.readInt(),
      addressModeU: r.readInt(),
      addressModeV: r.readInt(),
      addressModeW: r.readInt(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(label)
    writer.writeInt(magFilter)
    writer.writeInt(minFilter)
    writer.writeInt(mipmapFilter)
    writer.writeInt(addressModeU)
    writer.writeInt(addressModeV)
    writer.writeInt(addressModeW)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuBindGroupDescriptor: NitroEncodable {
  public var label: String
  public var layoutAddress: Int64
  public var entries: [GpuBindGroupEntry]

  public init(label: String, layoutAddress: Int64, entries: [GpuBindGroupEntry]) {
    self.label = label
    self.layoutAddress = layoutAddress
    self.entries = entries
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuBindGroupDescriptor {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuBindGroupDescriptor {
    return GpuBindGroupDescriptor(
      label: r.readString(),
      layoutAddress: r.readInt(),
      entries: (0..<Int(r.readInt32())).map { _ in GpuBindGroupEntry.fromReader(r) },
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(label)
    writer.writeInt(layoutAddress)
    writer.writeInt32(Int32(entries.count))
    for e in entries { e.writeFields(writer) }
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuComputePipelineDescriptor: NitroEncodable {
  public var label: String
  public var layoutAddress: Int64
  public var moduleAddress: Int64
  public var entryPoint: String

  public init(label: String, layoutAddress: Int64, moduleAddress: Int64, entryPoint: String) {
    self.label = label
    self.layoutAddress = layoutAddress
    self.moduleAddress = moduleAddress
    self.entryPoint = entryPoint
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuComputePipelineDescriptor {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuComputePipelineDescriptor {
    return GpuComputePipelineDescriptor(
      label: r.readString(),
      layoutAddress: r.readInt(),
      moduleAddress: r.readInt(),
      entryPoint: r.readString(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(label)
    writer.writeInt(layoutAddress)
    writer.writeInt(moduleAddress)
    writer.writeString(entryPoint)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuMappedData: NitroEncodable {
  public var data: Data

  public init(data: Data) {
    self.data = data
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuMappedData {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuMappedData {
    return GpuMappedData(
      data: r.readBlob(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBlob(data)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuTextureDescriptor: NitroEncodable {
  public var label: String
  public var width: Int64
  public var height: Int64
  public var format: Int64
  public var usage: Int64
  public var mipLevelCount: Int64
  public var sampleCount: Int64
  public var dimension: Int64
  public var depthOrArrayLayers: Int64

  public init(label: String, width: Int64, height: Int64, format: Int64, usage: Int64, mipLevelCount: Int64, sampleCount: Int64, dimension: Int64, depthOrArrayLayers: Int64) {
    self.label = label
    self.width = width
    self.height = height
    self.format = format
    self.usage = usage
    self.mipLevelCount = mipLevelCount
    self.sampleCount = sampleCount
    self.dimension = dimension
    self.depthOrArrayLayers = depthOrArrayLayers
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuTextureDescriptor {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuTextureDescriptor {
    return GpuTextureDescriptor(
      label: r.readString(),
      width: r.readInt(),
      height: r.readInt(),
      format: r.readInt(),
      usage: r.readInt(),
      mipLevelCount: r.readInt(),
      sampleCount: r.readInt(),
      dimension: r.readInt(),
      depthOrArrayLayers: r.readInt(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(label)
    writer.writeInt(width)
    writer.writeInt(height)
    writer.writeInt(format)
    writer.writeInt(usage)
    writer.writeInt(mipLevelCount)
    writer.writeInt(sampleCount)
    writer.writeInt(dimension)
    writer.writeInt(depthOrArrayLayers)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuTextureViewDescriptor: NitroEncodable {
  public var label: String
  public var baseMipLevel: Int64
  public var mipLevelCount: Int64
  public var dimension: Int64
  public var baseArrayLayer: Int64
  public var arrayLayerCount: Int64

  public init(label: String, baseMipLevel: Int64, mipLevelCount: Int64, dimension: Int64, baseArrayLayer: Int64, arrayLayerCount: Int64) {
    self.label = label
    self.baseMipLevel = baseMipLevel
    self.mipLevelCount = mipLevelCount
    self.dimension = dimension
    self.baseArrayLayer = baseArrayLayer
    self.arrayLayerCount = arrayLayerCount
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuTextureViewDescriptor {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuTextureViewDescriptor {
    return GpuTextureViewDescriptor(
      label: r.readString(),
      baseMipLevel: r.readInt(),
      mipLevelCount: r.readInt(),
      dimension: r.readInt(),
      baseArrayLayer: r.readInt(),
      arrayLayerCount: r.readInt(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(label)
    writer.writeInt(baseMipLevel)
    writer.writeInt(mipLevelCount)
    writer.writeInt(dimension)
    writer.writeInt(baseArrayLayer)
    writer.writeInt(arrayLayerCount)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuRequiredLimits: NitroEncodable {
  public var maxTextureDimension2D: Int64
  public var maxTextureArrayLayers: Int64
  public var maxBindGroups: Int64
  public var maxUniformBufferBindingSize: Int64
  public var maxStorageBufferBindingSize: Int64
  public var maxBufferSize: Int64
  public var maxComputeInvocationsPerWorkgroup: Int64

  public init(maxTextureDimension2D: Int64, maxTextureArrayLayers: Int64, maxBindGroups: Int64, maxUniformBufferBindingSize: Int64, maxStorageBufferBindingSize: Int64, maxBufferSize: Int64, maxComputeInvocationsPerWorkgroup: Int64) {
    self.maxTextureDimension2D = maxTextureDimension2D
    self.maxTextureArrayLayers = maxTextureArrayLayers
    self.maxBindGroups = maxBindGroups
    self.maxUniformBufferBindingSize = maxUniformBufferBindingSize
    self.maxStorageBufferBindingSize = maxStorageBufferBindingSize
    self.maxBufferSize = maxBufferSize
    self.maxComputeInvocationsPerWorkgroup = maxComputeInvocationsPerWorkgroup
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuRequiredLimits {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuRequiredLimits {
    return GpuRequiredLimits(
      maxTextureDimension2D: r.readInt(),
      maxTextureArrayLayers: r.readInt(),
      maxBindGroups: r.readInt(),
      maxUniformBufferBindingSize: r.readInt(),
      maxStorageBufferBindingSize: r.readInt(),
      maxBufferSize: r.readInt(),
      maxComputeInvocationsPerWorkgroup: r.readInt(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(maxTextureDimension2D)
    writer.writeInt(maxTextureArrayLayers)
    writer.writeInt(maxBindGroups)
    writer.writeInt(maxUniformBufferBindingSize)
    writer.writeInt(maxStorageBufferBindingSize)
    writer.writeInt(maxBufferSize)
    writer.writeInt(maxComputeInvocationsPerWorkgroup)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuRenderBundleEncoderDescriptor: NitroEncodable {
  public var label: String
  public var format0: Int64
  public var format1: Int64
  public var format2: Int64
  public var format3: Int64
  public var depthFormat: Int64
  public var sampleCount: Int64

  public init(label: String, format0: Int64, format1: Int64, format2: Int64, format3: Int64, depthFormat: Int64, sampleCount: Int64) {
    self.label = label
    self.format0 = format0
    self.format1 = format1
    self.format2 = format2
    self.format3 = format3
    self.depthFormat = depthFormat
    self.sampleCount = sampleCount
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuRenderBundleEncoderDescriptor {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuRenderBundleEncoderDescriptor {
    return GpuRenderBundleEncoderDescriptor(
      label: r.readString(),
      format0: r.readInt(),
      format1: r.readInt(),
      format2: r.readInt(),
      format3: r.readInt(),
      depthFormat: r.readInt(),
      sampleCount: r.readInt(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(label)
    writer.writeInt(format0)
    writer.writeInt(format1)
    writer.writeInt(format2)
    writer.writeInt(format3)
    writer.writeInt(depthFormat)
    writer.writeInt(sampleCount)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuColorAttachment: NitroEncodable {
  public var viewAddress: Int64
  public var loadOp: Int64
  public var storeOp: Int64
  public var clearR: Double
  public var clearG: Double
  public var clearB: Double
  public var clearA: Double
  public var resolveTargetAddress: Int64

  public init(viewAddress: Int64, loadOp: Int64, storeOp: Int64, clearR: Double, clearG: Double, clearB: Double, clearA: Double, resolveTargetAddress: Int64) {
    self.viewAddress = viewAddress
    self.loadOp = loadOp
    self.storeOp = storeOp
    self.clearR = clearR
    self.clearG = clearG
    self.clearB = clearB
    self.clearA = clearA
    self.resolveTargetAddress = resolveTargetAddress
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuColorAttachment {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuColorAttachment {
    return GpuColorAttachment(
      viewAddress: r.readInt(),
      loadOp: r.readInt(),
      storeOp: r.readInt(),
      clearR: r.readDouble(),
      clearG: r.readDouble(),
      clearB: r.readDouble(),
      clearA: r.readDouble(),
      resolveTargetAddress: r.readInt(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(viewAddress)
    writer.writeInt(loadOp)
    writer.writeInt(storeOp)
    writer.writeDouble(clearR)
    writer.writeDouble(clearG)
    writer.writeDouble(clearB)
    writer.writeDouble(clearA)
    writer.writeInt(resolveTargetAddress)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuRenderPassDescriptor: NitroEncodable {
  public var label: String
  public var colorAttachments: [GpuColorAttachment]
  public var timestampQuerySetAddress: Int64
  public var timestampBeginIndex: Int64
  public var timestampEndIndex: Int64
  public var depthViewAddress: Int64
  public var depthLoadOp: Int64
  public var depthStoreOp: Int64
  public var depthClearValue: Double
  public var stencilLoadOp: Int64
  public var stencilStoreOp: Int64
  public var stencilClearValue: Int64
  public var occlusionQuerySetAddress: Int64

  public init(label: String, colorAttachments: [GpuColorAttachment], timestampQuerySetAddress: Int64, timestampBeginIndex: Int64, timestampEndIndex: Int64, depthViewAddress: Int64, depthLoadOp: Int64, depthStoreOp: Int64, depthClearValue: Double, stencilLoadOp: Int64, stencilStoreOp: Int64, stencilClearValue: Int64, occlusionQuerySetAddress: Int64) {
    self.label = label
    self.colorAttachments = colorAttachments
    self.timestampQuerySetAddress = timestampQuerySetAddress
    self.timestampBeginIndex = timestampBeginIndex
    self.timestampEndIndex = timestampEndIndex
    self.depthViewAddress = depthViewAddress
    self.depthLoadOp = depthLoadOp
    self.depthStoreOp = depthStoreOp
    self.depthClearValue = depthClearValue
    self.stencilLoadOp = stencilLoadOp
    self.stencilStoreOp = stencilStoreOp
    self.stencilClearValue = stencilClearValue
    self.occlusionQuerySetAddress = occlusionQuerySetAddress
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuRenderPassDescriptor {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuRenderPassDescriptor {
    return GpuRenderPassDescriptor(
      label: r.readString(),
      colorAttachments: (0..<Int(r.readInt32())).map { _ in GpuColorAttachment.fromReader(r) },
      timestampQuerySetAddress: r.readInt(),
      timestampBeginIndex: r.readInt(),
      timestampEndIndex: r.readInt(),
      depthViewAddress: r.readInt(),
      depthLoadOp: r.readInt(),
      depthStoreOp: r.readInt(),
      depthClearValue: r.readDouble(),
      stencilLoadOp: r.readInt(),
      stencilStoreOp: r.readInt(),
      stencilClearValue: r.readInt(),
      occlusionQuerySetAddress: r.readInt(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(label)
    writer.writeInt32(Int32(colorAttachments.count))
    for e in colorAttachments { e.writeFields(writer) }
    writer.writeInt(timestampQuerySetAddress)
    writer.writeInt(timestampBeginIndex)
    writer.writeInt(timestampEndIndex)
    writer.writeInt(depthViewAddress)
    writer.writeInt(depthLoadOp)
    writer.writeInt(depthStoreOp)
    writer.writeDouble(depthClearValue)
    writer.writeInt(stencilLoadOp)
    writer.writeInt(stencilStoreOp)
    writer.writeInt(stencilClearValue)
    writer.writeInt(occlusionQuerySetAddress)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuVertexAttribute: NitroEncodable {
  public var format: Int64
  public var offset: Int64
  public var shaderLocation: Int64

  public init(format: Int64, offset: Int64, shaderLocation: Int64) {
    self.format = format
    self.offset = offset
    self.shaderLocation = shaderLocation
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuVertexAttribute {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuVertexAttribute {
    return GpuVertexAttribute(
      format: r.readInt(),
      offset: r.readInt(),
      shaderLocation: r.readInt(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(format)
    writer.writeInt(offset)
    writer.writeInt(shaderLocation)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuVertexBufferLayout: NitroEncodable {
  public var arrayStride: Int64
  public var stepMode: Int64
  public var attributes: [GpuVertexAttribute]

  public init(arrayStride: Int64, stepMode: Int64, attributes: [GpuVertexAttribute]) {
    self.arrayStride = arrayStride
    self.stepMode = stepMode
    self.attributes = attributes
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuVertexBufferLayout {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuVertexBufferLayout {
    return GpuVertexBufferLayout(
      arrayStride: r.readInt(),
      stepMode: r.readInt(),
      attributes: (0..<Int(r.readInt32())).map { _ in GpuVertexAttribute.fromReader(r) },
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(arrayStride)
    writer.writeInt(stepMode)
    writer.writeInt32(Int32(attributes.count))
    for e in attributes { e.writeFields(writer) }
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuBindGroupLayoutEntry: NitroEncodable {
  public var binding: Int64
  public var visibility: Int64
  public var type: Int64
  public var viewDimension: Int64
  public var hasDynamicOffset: Bool

  public init(binding: Int64, visibility: Int64, type: Int64, viewDimension: Int64, hasDynamicOffset: Bool) {
    self.binding = binding
    self.visibility = visibility
    self.type = type
    self.viewDimension = viewDimension
    self.hasDynamicOffset = hasDynamicOffset
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuBindGroupLayoutEntry {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuBindGroupLayoutEntry {
    return GpuBindGroupLayoutEntry(
      binding: r.readInt(),
      visibility: r.readInt(),
      type: r.readInt(),
      viewDimension: r.readInt(),
      hasDynamicOffset: r.readBool(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(binding)
    writer.writeInt(visibility)
    writer.writeInt(type)
    writer.writeInt(viewDimension)
    writer.writeBool(hasDynamicOffset)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuBindGroupLayoutDescriptor: NitroEncodable {
  public var label: String
  public var entries: [GpuBindGroupLayoutEntry]

  public init(label: String, entries: [GpuBindGroupLayoutEntry]) {
    self.label = label
    self.entries = entries
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuBindGroupLayoutDescriptor {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuBindGroupLayoutDescriptor {
    return GpuBindGroupLayoutDescriptor(
      label: r.readString(),
      entries: (0..<Int(r.readInt32())).map { _ in GpuBindGroupLayoutEntry.fromReader(r) },
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(label)
    writer.writeInt32(Int32(entries.count))
    for e in entries { e.writeFields(writer) }
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuPipelineLayoutDescriptor: NitroEncodable {
  public var label: String
  public var layout0: Int64
  public var layout1: Int64
  public var layout2: Int64
  public var layout3: Int64

  public init(label: String, layout0: Int64, layout1: Int64, layout2: Int64, layout3: Int64) {
    self.label = label
    self.layout0 = layout0
    self.layout1 = layout1
    self.layout2 = layout2
    self.layout3 = layout3
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuPipelineLayoutDescriptor {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuPipelineLayoutDescriptor {
    return GpuPipelineLayoutDescriptor(
      label: r.readString(),
      layout0: r.readInt(),
      layout1: r.readInt(),
      layout2: r.readInt(),
      layout3: r.readInt(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(label)
    writer.writeInt(layout0)
    writer.writeInt(layout1)
    writer.writeInt(layout2)
    writer.writeInt(layout3)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct GpuRenderPipelineDescriptor: NitroEncodable {
  public var label: String
  public var moduleAddress: Int64
  public var vertexEntryPoint: String
  public var fragmentEntryPoint: String
  public var targetFormat: Int64
  public var topology: Int64
  public var vertexBuffers: [GpuVertexBufferLayout]
  public var layoutAddress: Int64
  public var depthFormat: Int64
  public var depthWriteEnabled: Bool
  public var depthCompare: Int64
  public var blendMode: Int64
  public var sampleCount: Int64
  public var targetFormat1: Int64
  public var targetFormat2: Int64
  public var targetFormat3: Int64
  public var stencilCompare: Int64
  public var stencilFailOp: Int64
  public var stencilDepthFailOp: Int64
  public var stencilPassOp: Int64

  public init(label: String, moduleAddress: Int64, vertexEntryPoint: String, fragmentEntryPoint: String, targetFormat: Int64, topology: Int64, vertexBuffers: [GpuVertexBufferLayout], layoutAddress: Int64, depthFormat: Int64, depthWriteEnabled: Bool, depthCompare: Int64, blendMode: Int64, sampleCount: Int64, targetFormat1: Int64, targetFormat2: Int64, targetFormat3: Int64, stencilCompare: Int64, stencilFailOp: Int64, stencilDepthFailOp: Int64, stencilPassOp: Int64) {
    self.label = label
    self.moduleAddress = moduleAddress
    self.vertexEntryPoint = vertexEntryPoint
    self.fragmentEntryPoint = fragmentEntryPoint
    self.targetFormat = targetFormat
    self.topology = topology
    self.vertexBuffers = vertexBuffers
    self.layoutAddress = layoutAddress
    self.depthFormat = depthFormat
    self.depthWriteEnabled = depthWriteEnabled
    self.depthCompare = depthCompare
    self.blendMode = blendMode
    self.sampleCount = sampleCount
    self.targetFormat1 = targetFormat1
    self.targetFormat2 = targetFormat2
    self.targetFormat3 = targetFormat3
    self.stencilCompare = stencilCompare
    self.stencilFailOp = stencilFailOp
    self.stencilDepthFailOp = stencilDepthFailOp
    self.stencilPassOp = stencilPassOp
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> GpuRenderPipelineDescriptor {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> GpuRenderPipelineDescriptor {
    return GpuRenderPipelineDescriptor(
      label: r.readString(),
      moduleAddress: r.readInt(),
      vertexEntryPoint: r.readString(),
      fragmentEntryPoint: r.readString(),
      targetFormat: r.readInt(),
      topology: r.readInt(),
      vertexBuffers: (0..<Int(r.readInt32())).map { _ in GpuVertexBufferLayout.fromReader(r) },
      layoutAddress: r.readInt(),
      depthFormat: r.readInt(),
      depthWriteEnabled: r.readBool(),
      depthCompare: r.readInt(),
      blendMode: r.readInt(),
      sampleCount: r.readInt(),
      targetFormat1: r.readInt(),
      targetFormat2: r.readInt(),
      targetFormat3: r.readInt(),
      stencilCompare: r.readInt(),
      stencilFailOp: r.readInt(),
      stencilDepthFailOp: r.readInt(),
      stencilPassOp: r.readInt(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeString(label)
    writer.writeInt(moduleAddress)
    writer.writeString(vertexEntryPoint)
    writer.writeString(fragmentEntryPoint)
    writer.writeInt(targetFormat)
    writer.writeInt(topology)
    writer.writeInt32(Int32(vertexBuffers.count))
    for e in vertexBuffers { e.writeFields(writer) }
    writer.writeInt(layoutAddress)
    writer.writeInt(depthFormat)
    writer.writeBool(depthWriteEnabled)
    writer.writeInt(depthCompare)
    writer.writeInt(blendMode)
    writer.writeInt(sampleCount)
    writer.writeInt(targetFormat1)
    writer.writeInt(targetFormat2)
    writer.writeInt(targetFormat3)
    writer.writeInt(stencilCompare)
    writer.writeInt(stencilFailOp)
    writer.writeInt(stencilDepthFailOp)
    writer.writeInt(stencilPassOp)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

/**
 * Protocol for the NitroWebgpu module (NativeImpl.cpp).
 * Conform to this in your Swift/ObjC++ source code if you want
 * to delegate from the C++ HybridObject to a Swift implementation.
 * Nitro may call this implementation from any native thread.
 * Keep mutable state thread-safe or marshal work onto your own queue/actor.
 */
public protocol HybridNitroWebgpuProtocol: AnyObject {
    func initInstance(options: GpuInstanceOptions) -> Void
    func wgpuVersion() -> String
    func requestAdapter(options: GpuRequestAdapterOptions) async throws -> Int64
    func adapterGetInfo(adapter: Int64) -> GpuAdapterInfo
    func adapterGetLimits(adapter: Int64) -> GpuLimits
    func adapterHasTimestampQuery(adapter: Int64) -> Bool
    func adapterRelease(adapter: Int64) -> Void
    func requestDevice(adapter: Int64, descriptor: GpuDeviceDescriptor) async throws -> Int64
    func deviceGetQueue(device: Int64) -> Int64
    func deviceDestroy(device: Int64) -> Void
    func deviceRelease(device: Int64) -> Void
    func queueRelease(queue: Int64) -> Void
    func devicePushErrorScope(device: Int64, filter: Int64) -> Void
    func devicePopErrorScope(device: Int64) async throws -> GpuError?
    func deviceCreateBuffer(device: Int64, descriptor: GpuBufferDescriptor) -> Int64
    func bufferDestroy(buffer: Int64) -> Void
    func bufferRelease(buffer: Int64) -> Void
    func bufferGetSize(buffer: Int64) -> Int64
    func queueWriteBuffer(queue: Int64, buffer: Int64, bufferOffset: Int64, data: Data) -> Void
    func bufferMapRead(buffer: Int64, offset: Int64, size: Int64) async throws -> GpuMappedData
    func deviceCreateShaderModuleWgsl(device: Int64, label: String, wgsl: String) -> Int64
    func shaderModuleRelease(module: Int64) -> Void
    func deviceCreateComputePipeline(device: Int64, descriptor: GpuComputePipelineDescriptor) -> Int64
    func computePipelineRelease(pipeline: Int64) -> Void
    func computePipelineGetBindGroupLayout(pipeline: Int64, groupIndex: Int64) -> Int64
    func bindGroupLayoutRelease(layout: Int64) -> Void
    func deviceCreateBindGroup(device: Int64, descriptor: GpuBindGroupDescriptor) -> Int64
    func bindGroupRelease(bindGroup: Int64) -> Void
    func deviceCreateCommandEncoder(device: Int64, label: String) -> Int64
    func commandEncoderRelease(encoder: Int64) -> Void
    func encoderBeginComputePass(encoder: Int64, descriptor: GpuComputePassDescriptor) -> Int64
    func computePassSetPipeline(pass: Int64, pipeline: Int64) -> Void
    func computePassSetBindGroup(pass: Int64, index: Int64, bindGroup: Int64) -> Void
    func computePassDispatchWorkgroups(pass: Int64, x: Int64, y: Int64, z: Int64) -> Void
    func computePassEnd(pass: Int64) -> Void
    func computePassRelease(pass: Int64) -> Void
    func encoderCopyBufferToBuffer(encoder: Int64, src: Int64, srcOffset: Int64, dst: Int64, dstOffset: Int64, size: Int64) -> Void
    func encoderFinish(encoder: Int64, label: String) -> Int64
    func commandBufferRelease(commandBuffer: Int64) -> Void
    func queueSubmitOne(queue: Int64, commandBuffer: Int64) -> Void
    func queueOnSubmittedWorkDone(queue: Int64) async throws -> Void
    func deviceCreateTexture(device: Int64, descriptor: GpuTextureDescriptor) -> Int64
    func textureDestroy(texture: Int64) -> Void
    func textureRelease(texture: Int64) -> Void
    func textureCreateView(texture: Int64, descriptor: GpuTextureViewDescriptor) -> Int64
    func textureViewRelease(view: Int64) -> Void
    func queueWriteTexture(queue: Int64, texture: Int64, data: Data, bytesPerRow: Int64, width: Int64, height: Int64, mipLevel: Int64, arrayLayer: Int64) -> Void
    func deviceCreateSampler(device: Int64, descriptor: GpuSamplerDescriptor) -> Int64
    func samplerRelease(sampler: Int64) -> Void
    func deviceCreateRenderPipeline(device: Int64, descriptor: GpuRenderPipelineDescriptor) -> Int64
    func renderPipelineRelease(pipeline: Int64) -> Void
    func renderPipelineGetBindGroupLayout(pipeline: Int64, groupIndex: Int64) -> Int64
    func deviceCreateBindGroupLayout(device: Int64, descriptor: GpuBindGroupLayoutDescriptor) -> Int64
    func deviceCreatePipelineLayout(device: Int64, descriptor: GpuPipelineLayoutDescriptor) -> Int64
    func pipelineLayoutRelease(layout: Int64) -> Void
    func encoderBeginRenderPass(encoder: Int64, descriptor: GpuRenderPassDescriptor) -> Int64
    func renderPassSetPipeline(pass: Int64, pipeline: Int64) -> Void
    func renderPassSetBindGroup(pass: Int64, index: Int64, bindGroup: Int64) -> Void
    func renderPassSetVertexBuffer(pass: Int64, slot: Int64, buffer: Int64, offset: Int64) -> Void
    func renderPassSetIndexBuffer(pass: Int64, buffer: Int64, indexFormat: Int64, offset: Int64) -> Void
    func renderPassDraw(pass: Int64, vertexCount: Int64, instanceCount: Int64, firstVertex: Int64, firstInstance: Int64) -> Void
    func renderPassDrawIndexed(pass: Int64, indexCount: Int64, instanceCount: Int64, firstIndex: Int64, baseVertex: Int64, firstInstance: Int64) -> Void
    func renderPassEnd(pass: Int64) -> Void
    func renderPassRelease(pass: Int64) -> Void
    func encoderCopyTextureToBuffer(encoder: Int64, texture: Int64, buffer: Int64, bytesPerRow: Int64, width: Int64, height: Int64) -> Void
    func encoderCopyBufferToTexture(encoder: Int64, buffer: Int64, bytesPerRow: Int64, texture: Int64, mipLevel: Int64, width: Int64, height: Int64) -> Void
    func encoderCopyTextureToTexture(encoder: Int64, srcTexture: Int64, dstTexture: Int64, width: Int64, height: Int64) -> Void
    func renderPassSetViewport(pass: Int64, x: Double, y: Double, width: Double, height: Double, minDepth: Double, maxDepth: Double) -> Void
    func renderPassSetScissorRect(pass: Int64, x: Int64, y: Int64, width: Int64, height: Int64) -> Void
    func renderPassSetBlendConstant(pass: Int64, r: Double, g: Double, b: Double, a: Double) -> Void
    func renderPassDrawIndirect(pass: Int64, buffer: Int64, offset: Int64) -> Void
    func renderPassDrawIndexedIndirect(pass: Int64, buffer: Int64, offset: Int64) -> Void
    func computePassDispatchWorkgroupsIndirect(pass: Int64, buffer: Int64, offset: Int64) -> Void
    func deviceCreateOcclusionQuerySet(device: Int64, count: Int64) -> Int64
    func deviceGetLimits(device: Int64) -> GpuLimits
    func renderPassBeginOcclusionQuery(pass: Int64, queryIndex: Int64) -> Void
    func renderPassEndOcclusionQuery(pass: Int64) -> Void
    func renderPassSetStencilReference(pass: Int64, reference: Int64) -> Void
    func renderPassSetBindGroupOffsets(pass: Int64, index: Int64, bindGroup: Int64, offsetCount: Int64, o0: Int64, o1: Int64, o2: Int64, o3: Int64) -> Void
    func computePassSetBindGroupOffsets(pass: Int64, index: Int64, bindGroup: Int64, offsetCount: Int64, o0: Int64, o1: Int64, o2: Int64, o3: Int64) -> Void
    func deviceCreateRenderBundleEncoder(device: Int64, descriptor: GpuRenderBundleEncoderDescriptor) -> Int64
    func bundleSetPipeline(bundleEncoder: Int64, pipeline: Int64) -> Void
    func bundleSetBindGroup(bundleEncoder: Int64, index: Int64, bindGroup: Int64) -> Void
    func bundleSetVertexBuffer(bundleEncoder: Int64, slot: Int64, buffer: Int64, offset: Int64) -> Void
    func bundleSetIndexBuffer(bundleEncoder: Int64, buffer: Int64, indexFormat: Int64, offset: Int64) -> Void
    func bundleDraw(bundleEncoder: Int64, vertexCount: Int64, instanceCount: Int64, firstVertex: Int64, firstInstance: Int64) -> Void
    func bundleDrawIndexed(bundleEncoder: Int64, indexCount: Int64, instanceCount: Int64, firstIndex: Int64, baseVertex: Int64, firstInstance: Int64) -> Void
    func bundleFinish(bundleEncoder: Int64, label: String) -> Int64
    func renderBundleEncoderRelease(bundleEncoder: Int64) -> Void
    func renderBundleRelease(bundle: Int64) -> Void
    func renderPassExecuteBundle(pass: Int64, bundle: Int64) -> Void
    func deviceCreateTimestampQuerySet(device: Int64, count: Int64) -> Int64
    func querySetRelease(querySet: Int64) -> Void
    func encoderResolveQuerySet(encoder: Int64, querySet: Int64, firstQuery: Int64, queryCount: Int64, destination: Int64, destinationOffset: Int64) -> Void
    func queueTimestampPeriod(queue: Int64) -> Double
    var uncapturedErrors: AnyPublisher<GpuUncapturedError, Never> { get }
    var deviceLostEvents: AnyPublisher<GpuDeviceLost, Never> { get }
}

public class NitroWebgpuRegistry {
    public static var impl: HybridNitroWebgpuProtocol?

    public static func register(_ impl: HybridNitroWebgpuProtocol) {
        NitroWebgpuRegistry.impl = impl
    }

    // Stream: uncapturedErrors cancellables keyed by dartPort
    public static var _uncapturedErrorsCancellables = [Int64: AnyCancellable]()

    // Stream: deviceLostEvents cancellables keyed by dartPort
    public static var _deviceLostEventsCancellables = [Int64: AnyCancellable]()
}

// NOTE: @_cdecl bridge stubs are NOT generated for NativeImpl.cpp modules.
// The .bridge.g.mm C++ shim calls nitro_webgpu_xxx() C functions directly.
