// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.5.12
// Generated from: nitro_webgpu.native.dart
// ignore_for_file: no_leading_underscores_for_local_identifiers, prefer_typing_uninitialized_variables, non_constant_identifier_names, unused_element, unused_field
part of 'nitro_webgpu.native.dart';

class _NitroWebgpuImpl extends NitroWebgpu {
  final DynamicLibrary _dylib;
  static final _instances = <String, _NitroWebgpuImpl>{};
  final String _instanceKey;
  late final int _instanceId;
  final Pointer<NitroErrorFfi> _nitroErr = calloc<NitroErrorFfi>();
  late final void Function(Pointer<Void>) _nitroFreePtr = _dylib
      .lookupFunction<
        Void Function(Pointer<Void>),
        void Function(Pointer<Void>)
      >('nitro_webgpu_nitro_free');
  void _nitroFree(Pointer<NativeType> ptr) => _nitroFreePtr(ptr.cast());
  late final Pointer<NativeFinalizerFunction> _nitroFreeFinalizer = _dylib
      .lookup<NativeFinalizerFunction>('nitro_webgpu_nitro_free')
      .cast();
  late final Pointer<Void> Function(int) _nitroAllocPtr = _dylib
      .lookupFunction<
        Pointer<Void> Function(IntPtr),
        Pointer<Void> Function(int)
      >('nitro_webgpu_nitro_alloc');
  late final NitroNativeAllocator _nitroNativeAllocator = NitroNativeAllocator(
    _nitroAllocPtr,
    _nitroFreePtr,
  );

  static DynamicLibrary _loadSupportedLibrary() {
    return NitroRuntime.loadLibForTargets(
      'nitro_webgpu',
      ios: true,
      android: true,
      macos: true,
      windows: true,
      linux: true,
      web: false,
    );
  }

  factory _NitroWebgpuImpl([String key = 'default']) {
    return _instances.putIfAbsent(key, () => _NitroWebgpuImpl._init(key));
  }

  _NitroWebgpuImpl._init(this._instanceKey) : _dylib = _loadSupportedLibrary() {
    final initSw = Stopwatch()..start();
    assert(
      sizeOf<IntPtr>() >= 4,
      'nitro_webgpu: unsupported pointer width ${sizeOf<IntPtr>()}B',
    );
    final initFunc = _dylib
        .lookupFunction<
          IntPtr Function(Pointer<Void>),
          int Function(Pointer<Void>)
        >('nitro_webgpu_init_dart_api_dl');
    final initCode = initFunc(NativeApi.initializeApiDLData);
    if (initCode != 0) {
      throw StateError(
        'nitro_webgpu: Dart API DL initialization failed with code $initCode.',
      );
    }
    if (!_dylib.providesSymbol('nitro_webgpu_nitro_abi_version')) {
      throw StateError(
        'nitro_webgpu: missing nitro_webgpu_nitro_abi_version — plugin must be rebuilt against the current Nitro version.',
      );
    }
    NitroRuntime.checkAbiVersion(
      'nitro_webgpu',
      () => _dylib.lookupFunction<Uint32 Function(), int Function()>(
        'nitro_webgpu_nitro_abi_version',
      )(),
    );
    if (!_dylib.providesSymbol('nitro_webgpu_nitro_bridge_checksum')) {
      throw StateError(
        'nitro_webgpu: missing nitro_webgpu_nitro_bridge_checksum — plugin must be rebuilt against the current Nitro version.',
      );
    }
    NitroRuntime.checkLinkChecksum(
      'nitro_webgpu',
      '4792d7ab9819e4f4',
      () => _dylib
          .lookupFunction<Pointer<Utf8> Function(), Pointer<Utf8> Function()>(
            'nitro_webgpu_nitro_bridge_checksum',
          )()
          .toDartString(),
    );
    final _keyPtr = _instanceKey.toNativeUtf8(allocator: calloc);
    try {
      _instanceId = _createInstancePtr(_keyPtr);
      if (_instanceId < 0) {
        throw StateError(
          'nitro_webgpu: failed to create native instance for key "$_instanceKey".',
        );
      }
    } finally {
      calloc.free(_keyPtr);
    }
    NitroInstanceRegistry.register(_instanceId, this);
    initSw.stop();
    NitroRuntime.logLifecycle(
      'init(nitro_webgpu)',
      'initialized in ${initSw.elapsedMicroseconds} µs (instanceId=$_instanceId)',
    );
  }

  late final int Function(Pointer<Utf8>) _createInstancePtr = _dylib
      .lookupFunction<
        Int64 Function(Pointer<Utf8>),
        int Function(Pointer<Utf8>)
      >('nitro_webgpu_create_instance');
  late final void Function(int) _destroyInstancePtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_webgpu_destroy_instance',
      );
  late final double Function(int, double, double, Pointer<NitroErrorFfi>)
  _addPtr = _dylib
      .lookup<
        NativeFunction<
          Double Function(Int64, Double, Double, Pointer<NitroErrorFfi>)
        >
      >('nitro_webgpu_add')
      .asFunction<double Function(int, double, double, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final Pointer<Utf8> Function(int, Pointer<Utf8>) _getGreetingPtr = _dylib
      .lookupFunction<
        Pointer<Utf8> Function(Int64, Pointer<Utf8>),
        Pointer<Utf8> Function(int, Pointer<Utf8>)
      >('nitro_webgpu_get_greeting');
  // ignore: unused_field
  late final Pointer<NitroErrorFfi> Function() _getErrorPtr = _dylib
      .lookupFunction<
        Pointer<NitroErrorFfi> Function(),
        Pointer<NitroErrorFfi> Function()
      >('nitro_webgpu_get_error');
  // ignore: unused_field
  late final void Function() _clearErrorPtr = _dylib
      .lookupFunction<Void Function(), void Function()>(
        'nitro_webgpu_clear_error',
      );
  // ignore: unused_field
  late final Pointer<NativeFunction<Pointer<NitroErrorFfi> Function()>>
  _getErrorNativePtr = _dylib.lookup('nitro_webgpu_get_error');
  // ignore: unused_field
  late final Pointer<NativeFunction<Void Function()>> _clearErrorNativePtr =
      _dylib.lookup('nitro_webgpu_clear_error');

  @override
  void dispose() {
    if (isDisposed) return;
    NitroRuntime.logLifecycle(
      'dispose(nitro_webgpu)',
      'disposing (instanceId=$_instanceId)',
    );
    _destroyInstancePtr(_instanceId);
    NitroRuntime.releaseLib('nitro_webgpu');
    _instances.remove(_instanceKey);
    NitroInstanceRegistry.unregister(_instanceId, this);
    calloc.free(_nitroErr); // S8: free pre-allocated error slot
    super.dispose(); // sets isDisposed = true, calls onDestroy()
    NitroRuntime.logLifecycle('dispose(nitro_webgpu)', 'disposed');
  }

  /// Opaque reference to this native impl — pass to other plugins via AnyNativeObject.
  AnyNativeObject get asAnyNativeObject => AnyNativeObject(_instanceId);

  @override
  double add(double a, double b) {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _addPtr(_instanceId, a, b, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      return res;
    }, methodName: 'add');
  }

  @override
  Future<String> getGreeting(String name) async {
    checkDisposed();
    final arena = Arena();
    try {
      final res = await NitroRuntime.callAsync<Pointer<Utf8>>(
        _getGreetingPtr,
        [_instanceId, name.toNativeUtf8(allocator: arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'getGreeting',
      );
      return res.toDartStringFreedBy(_nitroFree);
    } finally {
      arena.releaseAll();
    }
  }
}

extension NitroWebgpuNativeRef on NitroWebgpu {
  AnyNativeObject get asAnyNativeObject =>
      (this as _NitroWebgpuImpl).asAnyNativeObject;
}
