// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.5.14
// Generated from: nitro_webgpu_present.native.dart
// ignore_for_file: no_leading_underscores_for_local_identifiers, prefer_typing_uninitialized_variables, non_constant_identifier_names, unused_element, unused_field
part of 'nitro_webgpu_present.native.dart';

class _NitroWebgpuPresentImpl extends NitroWebgpuPresent {
  final DynamicLibrary _dylib;
  static final _instances = <String, _NitroWebgpuPresentImpl>{};
  final String _instanceKey;
  late final int _instanceId;
  final Pointer<NitroErrorFfi> _nitroErr = calloc<NitroErrorFfi>();
  late final void Function(Pointer<Void>) _nitroFreePtr = _dylib
      .lookupFunction<
        Void Function(Pointer<Void>),
        void Function(Pointer<Void>)
      >('nitro_webgpu_present_nitro_free');
  void _nitroFree(Pointer<NativeType> ptr) => _nitroFreePtr(ptr.cast());
  late final Pointer<NativeFinalizerFunction> _nitroFreeFinalizer = _dylib
      .lookup<NativeFinalizerFunction>('nitro_webgpu_present_nitro_free')
      .cast();
  late final Pointer<Void> Function(int) _nitroAllocPtr = _dylib
      .lookupFunction<
        Pointer<Void> Function(IntPtr),
        Pointer<Void> Function(int)
      >('nitro_webgpu_present_nitro_alloc');
  late final NitroNativeAllocator _nitroNativeAllocator = NitroNativeAllocator(
    _nitroAllocPtr,
    _nitroFreePtr,
  );

  static DynamicLibrary _loadSupportedLibrary() {
    return NitroRuntime.loadLibForTargets(
      'nitro_webgpu_present',
      ios: true,
      android: true,
      macos: true,
      windows: true,
      linux: true,
      web: false,
    );
  }

  factory _NitroWebgpuPresentImpl([String key = 'default']) {
    return _instances.putIfAbsent(
      key,
      () => _NitroWebgpuPresentImpl._init(key),
    );
  }

  _NitroWebgpuPresentImpl._init(this._instanceKey)
    : _dylib = _loadSupportedLibrary() {
    final initSw = Stopwatch()..start();
    assert(
      sizeOf<IntPtr>() >= 4,
      'nitro_webgpu_present: unsupported pointer width ${sizeOf<IntPtr>()}B',
    );
    final initFunc = _dylib
        .lookupFunction<
          IntPtr Function(Pointer<Void>),
          int Function(Pointer<Void>)
        >('nitro_webgpu_present_init_dart_api_dl');
    final initCode = initFunc(NativeApi.initializeApiDLData);
    if (initCode != 0) {
      throw StateError(
        'nitro_webgpu_present: Dart API DL initialization failed with code $initCode.',
      );
    }
    if (!_dylib.providesSymbol('nitro_webgpu_present_nitro_abi_version')) {
      throw StateError(
        'nitro_webgpu_present: missing nitro_webgpu_present_nitro_abi_version — plugin must be rebuilt against the current Nitro version.',
      );
    }
    NitroRuntime.checkAbiVersion(
      'nitro_webgpu_present',
      () => _dylib.lookupFunction<Uint32 Function(), int Function()>(
        'nitro_webgpu_present_nitro_abi_version',
      )(),
    );
    if (!_dylib.providesSymbol('nitro_webgpu_present_nitro_bridge_checksum')) {
      throw StateError(
        'nitro_webgpu_present: missing nitro_webgpu_present_nitro_bridge_checksum — plugin must be rebuilt against the current Nitro version.',
      );
    }
    NitroRuntime.checkLinkChecksum(
      'nitro_webgpu_present',
      '7297a1bc42747154',
      () => _dylib
          .lookupFunction<Pointer<Utf8> Function(), Pointer<Utf8> Function()>(
            'nitro_webgpu_present_nitro_bridge_checksum',
          )()
          .toDartString(),
    );
    final _keyPtr = _instanceKey.toNativeUtf8(allocator: calloc);
    try {
      _instanceId = _createInstancePtr(_keyPtr);
      if (_instanceId < 0) {
        throw StateError(
          'nitro_webgpu_present: failed to create native instance for key "$_instanceKey".',
        );
      }
    } finally {
      calloc.free(_keyPtr);
    }
    NitroInstanceRegistry.register(_instanceId, this);
    initSw.stop();
    NitroRuntime.logLifecycle(
      'init(nitro_webgpu_present)',
      'initialized in ${initSw.elapsedMicroseconds} µs (instanceId=$_instanceId)',
    );
  }

  late final int Function(Pointer<Utf8>) _createInstancePtr = _dylib
      .lookupFunction<
        Int64 Function(Pointer<Utf8>),
        int Function(Pointer<Utf8>)
      >('nitro_webgpu_present_create_instance');
  late final void Function(int) _destroyInstancePtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_webgpu_present_destroy_instance',
      );
  late final int Function(int, int, int, int, Pointer<NitroErrorFfi>)
  _createPresenterPtr = _dylib
      .lookup<
        NativeFunction<
          Int64 Function(Int64, Int64, Int64, Int64, Pointer<NitroErrorFfi>)
        >
      >('nitro_webgpu_present_create_presenter')
      .asFunction<int Function(int, int, int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final int Function(int, int, Pointer<NitroErrorFfi>)
  _flutterTextureIdPtr = _dylib
      .lookup<
        NativeFunction<Int64 Function(Int64, Int64, Pointer<NitroErrorFfi>)>
      >('nitro_webgpu_present_flutter_texture_id')
      .asFunction<int Function(int, int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(int, int, Pointer<NitroErrorFfi>, int)
  _acquireFramePtr = _dylib
      .lookupFunction<
        Void Function(Int64, Int64, Pointer<NitroErrorFfi>, Int64),
        void Function(int, int, Pointer<NitroErrorFfi>, int)
      >('nitro_webgpu_present_acquire_frame');
  late final int Function(int, int, Pointer<NitroErrorFfi>)
  _acquireFrameSyncPtr = _dylib
      .lookup<
        NativeFunction<Int64 Function(Int64, Int64, Pointer<NitroErrorFfi>)>
      >('nitro_webgpu_present_acquire_frame_sync')
      .asFunction<int Function(int, int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(int, int, Pointer<NitroErrorFfi>) _presentFramePtr =
      _dylib
          .lookup<
            NativeFunction<Void Function(Int64, Int64, Pointer<NitroErrorFfi>)>
          >('nitro_webgpu_present_present_frame')
          .asFunction<void Function(int, int, Pointer<NitroErrorFfi>)>(
            isLeaf: true,
          );
  late final int Function(int, int, Pointer<NitroErrorFfi>)
  _presenterFormatPtr = _dylib
      .lookup<
        NativeFunction<Int64 Function(Int64, Int64, Pointer<NitroErrorFfi>)>
      >('nitro_webgpu_present_presenter_format')
      .asFunction<int Function(int, int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final bool Function(int, int, Pointer<NitroErrorFfi>)
  _presenterUsesGpuPathPtr = _dylib
      .lookup<
        NativeFunction<Bool Function(Int64, Int64, Pointer<NitroErrorFfi>)>
      >('nitro_webgpu_present_presenter_uses_gpu_path')
      .asFunction<bool Function(int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, int, int, Pointer<NitroErrorFfi>)
  _resizePresenterPtr = _dylib
      .lookup<
        NativeFunction<
          Void Function(Int64, Int64, Int64, Int64, Pointer<NitroErrorFfi>)
        >
      >('nitro_webgpu_present_resize_presenter')
      .asFunction<void Function(int, int, int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, int, int, int, Pointer<NitroErrorFfi>)
  _presenterSetSurfaceSizePtr = _dylib
      .lookup<
        NativeFunction<
          Void Function(Int64, Int64, Int64, Int64, Pointer<NitroErrorFfi>)
        >
      >('nitro_webgpu_present_presenter_set_surface_size')
      .asFunction<void Function(int, int, int, int, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final double Function(int, Pointer<NitroErrorFfi>)
  _requestMaxRefreshRatePtr = _dylib
      .lookup<NativeFunction<Double Function(Int64, Pointer<NitroErrorFfi>)>>(
        'nitro_webgpu_present_request_max_refresh_rate',
      )
      .asFunction<double Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(int, int, Pointer<NitroErrorFfi>, int)
  _destroyPresenterPtr = _dylib
      .lookupFunction<
        Void Function(Int64, Int64, Pointer<NitroErrorFfi>, Int64),
        void Function(int, int, Pointer<NitroErrorFfi>, int)
      >('nitro_webgpu_present_destroy_presenter');
  // ignore: unused_field
  late final Pointer<NitroErrorFfi> Function() _getErrorPtr = _dylib
      .lookupFunction<
        Pointer<NitroErrorFfi> Function(),
        Pointer<NitroErrorFfi> Function()
      >('nitro_webgpu_present_get_error');
  // ignore: unused_field
  late final void Function() _clearErrorPtr = _dylib
      .lookupFunction<Void Function(), void Function()>(
        'nitro_webgpu_present_clear_error',
      );

  @override
  void dispose() {
    if (isDisposed) return;
    NitroRuntime.logLifecycle(
      'dispose(nitro_webgpu_present)',
      'disposing (instanceId=$_instanceId)',
    );
    _destroyInstancePtr(_instanceId);
    NitroRuntime.releaseLib('nitro_webgpu_present');
    _instances.remove(_instanceKey);
    NitroInstanceRegistry.unregister(_instanceId, this);
    calloc.free(_nitroErr); // S8: free pre-allocated error slot
    super.dispose(); // sets isDisposed = true, calls onDestroy()
    NitroRuntime.logLifecycle('dispose(nitro_webgpu_present)', 'disposed');
  }

  /// Opaque reference to this native impl — pass to other plugins via AnyNativeObject.
  AnyNativeObject get asAnyNativeObject => AnyNativeObject(_instanceId);

  @override
  int createPresenter(int deviceAddress, int widthPx, int heightPx) {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _createPresenterPtr(
        _instanceId,
        deviceAddress,
        widthPx,
        heightPx,
        _nitroErr,
      );
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      return res;
    }, methodName: 'createPresenter');
  }

  @override
  int flutterTextureId(int token) {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _flutterTextureIdPtr(_instanceId, token, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      return res;
    }, methodName: 'flutterTextureId');
  }

  @override
  Future<int> acquireFrame(int token) {
    checkDisposed();
    final _nitroErr = calloc<NitroErrorFfi>();
    return NitroRuntime.openNativeAsync<int>(
      call: (port) => _acquireFramePtr(_instanceId, token, _nitroErr, port),
      unpack: (raw) {
        NitroRuntime.throwIfOutParamErrorAndFree(
          _nitroErr,
          nativeFree: _nitroFree,
        );
        return ((raw) => raw as int)(raw);
      },
      methodName: 'acquireFrame',
    );
  }

  @override
  int acquireFrameSync(int token) {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _acquireFrameSyncPtr(_instanceId, token, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      return res;
    }, methodName: 'acquireFrameSync');
  }

  @override
  void presentFrame(int token) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _presentFramePtr(_instanceId, token, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
    }, methodName: 'presentFrame');
  }

  @override
  int presenterFormat(int token) {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _presenterFormatPtr(_instanceId, token, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      return res;
    }, methodName: 'presenterFormat');
  }

  @override
  bool presenterUsesGpuPath(int token) {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _presenterUsesGpuPathPtr(_instanceId, token, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      return res;
    }, methodName: 'presenterUsesGpuPath');
  }

  @override
  void resizePresenter(int token, int widthPx, int heightPx) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _resizePresenterPtr(_instanceId, token, widthPx, heightPx, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
    }, methodName: 'resizePresenter');
  }

  @override
  void presenterSetSurfaceSize(int token, int widthPx, int heightPx) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _presenterSetSurfaceSizePtr(
        _instanceId,
        token,
        widthPx,
        heightPx,
        _nitroErr,
      );
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
    }, methodName: 'presenterSetSurfaceSize');
  }

  @override
  double requestMaxRefreshRate() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _requestMaxRefreshRatePtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
      return res;
    }, methodName: 'requestMaxRefreshRate');
  }

  @override
  Future<void> destroyPresenter(int token) {
    checkDisposed();
    final _nitroErr = calloc<NitroErrorFfi>();
    return NitroRuntime.openNativeAsync<void>(
      call: (port) => _destroyPresenterPtr(_instanceId, token, _nitroErr, port),
      unpack: (raw) {
        NitroRuntime.throwIfOutParamErrorAndFree(
          _nitroErr,
          nativeFree: _nitroFree,
        );
        return ((_) {})(raw);
      },
      methodName: 'destroyPresenter',
    );
  }
}

extension NitroWebgpuPresentNativeRef on NitroWebgpuPresent {
  AnyNativeObject get asAnyNativeObject =>
      (this as _NitroWebgpuPresentImpl).asAnyNativeObject;
}
