// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.5.12
// Generated from: nitro_webgpu.native.dart
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

#ifndef NITRO_EXPORT
#  if defined(_WIN32)
#    define NITRO_EXPORT __declspec(dllexport)
#  else
#    define NITRO_EXPORT __attribute__((visibility("default"))) __attribute__((used))
#  endif
#endif

#ifndef NITRO_ERROR_DEFINED
#define NITRO_ERROR_DEFINED
typedef struct {
  int8_t hasError;
  const char* name;
  const char* message;
  const char* code;
  const char* stackTrace;
} NitroError;
#endif

#ifndef NITRO_OPT_DEFINED
#define NITRO_OPT_DEFINED
#pragma pack(push, 1)
typedef struct { uint8_t hasValue; int64_t  value; } NitroOptInt64;
typedef struct { uint8_t hasValue; double   value; } NitroOptFloat64;
typedef struct { uint8_t hasValue; uint8_t  value; } NitroOptBool;
#pragma pack(pop)
#endif

#ifdef __cplusplus
extern "C" {
#endif

NITRO_EXPORT uint32_t nitro_webgpu_nitro_abi_version(void);
NITRO_EXPORT const char* nitro_webgpu_nitro_bridge_checksum(void);
NITRO_EXPORT intptr_t nitro_webgpu_init_dart_api_dl(void* data);
NITRO_EXPORT NitroError* nitro_webgpu_get_error(void);
NITRO_EXPORT void nitro_webgpu_clear_error(void);
NITRO_EXPORT int64_t nitro_webgpu_create_instance(const char* key);
NITRO_EXPORT void nitro_webgpu_destroy_instance(int64_t instanceId);
NITRO_EXPORT void nitro_webgpu_nitro_free(void* ptr);
NITRO_EXPORT void* nitro_webgpu_nitro_alloc(size_t size);



// Methods
NITRO_EXPORT void nitro_webgpu_init_instance(int64_t instanceId, void* options, NitroError* _nitro_err);
NITRO_EXPORT const char* nitro_webgpu_wgpu_version(int64_t instanceId, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_request_adapter(int64_t instanceId, void* options, NitroError* _nitro_err, int64_t dart_port);
NITRO_EXPORT void* nitro_webgpu_adapter_get_info(int64_t instanceId, int64_t adapter, NitroError* _nitro_err);
NITRO_EXPORT void* nitro_webgpu_adapter_get_limits(int64_t instanceId, int64_t adapter, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_adapter_release(int64_t instanceId, int64_t adapter, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_request_device(int64_t instanceId, int64_t adapter, void* descriptor, NitroError* _nitro_err, int64_t dart_port);
NITRO_EXPORT int64_t nitro_webgpu_device_get_queue(int64_t instanceId, int64_t device, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_device_destroy(int64_t instanceId, int64_t device, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_device_release(int64_t instanceId, int64_t device, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_queue_release(int64_t instanceId, int64_t queue, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_device_push_error_scope(int64_t instanceId, int64_t device, int64_t filter, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_device_pop_error_scope(int64_t instanceId, int64_t device, NitroError* _nitro_err, int64_t dart_port);
NITRO_EXPORT int64_t nitro_webgpu_device_create_buffer(int64_t instanceId, int64_t device, void* descriptor, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_buffer_destroy(int64_t instanceId, int64_t buffer, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_buffer_release(int64_t instanceId, int64_t buffer, NitroError* _nitro_err);
NITRO_EXPORT int64_t nitro_webgpu_buffer_get_size(int64_t instanceId, int64_t buffer, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_queue_write_buffer(int64_t instanceId, int64_t queue, int64_t buffer, int64_t bufferOffset, uint8_t* data, size_t data_length, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_buffer_map_read(int64_t instanceId, int64_t buffer, int64_t offset, int64_t size, NitroError* _nitro_err, int64_t dart_port);
NITRO_EXPORT int64_t nitro_webgpu_device_create_shader_module_wgsl(int64_t instanceId, int64_t device, const char* label, const char* wgsl, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_shader_module_release(int64_t instanceId, int64_t module, NitroError* _nitro_err);
NITRO_EXPORT int64_t nitro_webgpu_device_create_compute_pipeline(int64_t instanceId, int64_t device, void* descriptor, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_compute_pipeline_release(int64_t instanceId, int64_t pipeline, NitroError* _nitro_err);
NITRO_EXPORT int64_t nitro_webgpu_compute_pipeline_get_bind_group_layout(int64_t instanceId, int64_t pipeline, int64_t groupIndex, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_bind_group_layout_release(int64_t instanceId, int64_t layout, NitroError* _nitro_err);
NITRO_EXPORT int64_t nitro_webgpu_device_create_bind_group(int64_t instanceId, int64_t device, void* descriptor, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_bind_group_release(int64_t instanceId, int64_t bindGroup, NitroError* _nitro_err);
NITRO_EXPORT int64_t nitro_webgpu_device_create_command_encoder(int64_t instanceId, int64_t device, const char* label, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_command_encoder_release(int64_t instanceId, int64_t encoder, NitroError* _nitro_err);
NITRO_EXPORT int64_t nitro_webgpu_encoder_begin_compute_pass(int64_t instanceId, int64_t encoder, const char* label, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_compute_pass_set_pipeline(int64_t instanceId, int64_t pass, int64_t pipeline, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_compute_pass_set_bind_group(int64_t instanceId, int64_t pass, int64_t index, int64_t bindGroup, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_compute_pass_dispatch_workgroups(int64_t instanceId, int64_t pass, int64_t x, int64_t y, int64_t z, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_compute_pass_end(int64_t instanceId, int64_t pass, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_compute_pass_release(int64_t instanceId, int64_t pass, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_encoder_copy_buffer_to_buffer(int64_t instanceId, int64_t encoder, int64_t src, int64_t srcOffset, int64_t dst, int64_t dstOffset, int64_t size, NitroError* _nitro_err);
NITRO_EXPORT int64_t nitro_webgpu_encoder_finish(int64_t instanceId, int64_t encoder, const char* label, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_command_buffer_release(int64_t instanceId, int64_t commandBuffer, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_queue_submit_one(int64_t instanceId, int64_t queue, int64_t commandBuffer, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_queue_on_submitted_work_done(int64_t instanceId, int64_t queue, NitroError* _nitro_err, int64_t dart_port);
NITRO_EXPORT int64_t nitro_webgpu_device_create_texture(int64_t instanceId, int64_t device, void* descriptor, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_texture_destroy(int64_t instanceId, int64_t texture, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_texture_release(int64_t instanceId, int64_t texture, NitroError* _nitro_err);
NITRO_EXPORT int64_t nitro_webgpu_texture_create_view(int64_t instanceId, int64_t texture, const char* label, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_texture_view_release(int64_t instanceId, int64_t view, NitroError* _nitro_err);
NITRO_EXPORT int64_t nitro_webgpu_device_create_render_pipeline(int64_t instanceId, int64_t device, void* descriptor, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_render_pipeline_release(int64_t instanceId, int64_t pipeline, NitroError* _nitro_err);
NITRO_EXPORT int64_t nitro_webgpu_encoder_begin_render_pass(int64_t instanceId, int64_t encoder, void* descriptor, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_render_pass_set_pipeline(int64_t instanceId, int64_t pass, int64_t pipeline, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_render_pass_draw(int64_t instanceId, int64_t pass, int64_t vertexCount, int64_t instanceCount, int64_t firstVertex, int64_t firstInstance, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_render_pass_end(int64_t instanceId, int64_t pass, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_render_pass_release(int64_t instanceId, int64_t pass, NitroError* _nitro_err);
NITRO_EXPORT void nitro_webgpu_encoder_copy_texture_to_buffer(int64_t instanceId, int64_t encoder, int64_t texture, int64_t buffer, int64_t bytesPerRow, int64_t width, int64_t height, NitroError* _nitro_err);

// Streams
// Stream<GpuUncapturedError> uncapturedErrors
NITRO_EXPORT void nitro_webgpu_register_uncaptured_errors_stream(int64_t instanceId, int64_t dart_port);
NITRO_EXPORT void nitro_webgpu_release_uncaptured_errors_stream(int64_t dart_port);
// Stream<GpuDeviceLost> deviceLostEvents
NITRO_EXPORT void nitro_webgpu_register_device_lost_events_stream(int64_t instanceId, int64_t dart_port);
NITRO_EXPORT void nitro_webgpu_release_device_lost_events_stream(int64_t dart_port);

#ifdef __cplusplus
}
#endif
