package dev.shreeman.nitro_webgpu

import nitro.nitro_webgpu_module.HybridNitroWebgpuSpec

/// Native implementation of HybridNitroWebgpuSpec.
/// This file is yours to edit — the interface is generated by `nitrogen generate`.
/// Use `applicationContext` (from the interface) to access the Android context.
class NitroWebgpuImpl : HybridNitroWebgpuSpec {

    override fun add(a: Double, b: Double): Double = a + b

    override suspend fun getGreeting(name: String): String = "Hello, $name!"
}
