// HybridNitroWebgpu — WindowsNativeImpl.cpp implementation.
// Generated by nitrogen link. Fill in the method bodies.
#include "../../lib/src/generated/cpp/nitro_webgpu.native.g.h"

#include <string>

class HybridNitroWebgpuImpl final : public HybridNitroWebgpu {
public:
    // TODO: implement all pure-virtual methods declared in HybridNitroWebgpu
};

// MSVC static-initializer auto-registration (no __attribute__((constructor)) on Windows).
namespace {
  struct _AutoRegister {
    _AutoRegister() { nitro_webgpu_register_impl(new HybridNitroWebgpuImpl()); }
  };
  static _AutoRegister _auto_register_instance;
}
