// HybridNitroWebgpuPresent — WindowsNativeImpl.cpp implementation.
// Generated by nitrogen link. Fill in the method bodies.
#include "../../lib/src/generated/cpp/nitro_webgpu_present.native.g.h"

#include <string>

class HybridNitroWebgpuPresentImpl final : public HybridNitroWebgpuPresent {
public:
    // TODO: implement all pure-virtual methods declared in HybridNitroWebgpuPresent
};

// MSVC static-initializer auto-registration (no __attribute__((constructor)) on Windows).
namespace {
  struct _AutoRegister {
    _AutoRegister() { nitro_webgpu_present_register_impl(new HybridNitroWebgpuPresentImpl()); }
  };
  static _AutoRegister _auto_register_instance;
}
