// HybridNitroWebgpuPresent — LinuxNativeImpl.cpp implementation.
// Generated by nitrogen init. Fill in the method bodies.
#include "../../lib/src/generated/cpp/nitro_webgpu_present.native.g.h"

#include <string>

class HybridNitroWebgpuPresentImpl final : public HybridNitroWebgpuPresent {
public:
    // TODO: implement all pure-virtual methods declared in HybridNitroWebgpuPresent
};

// GCC/Clang auto-registration via constructor attribute.
__attribute__((constructor))
static void nitro_auto_register() {
    nitro_webgpu_present_register_impl(new HybridNitroWebgpuPresentImpl());
}
