// HybridNitroWebgpu — LinuxNativeImpl.cpp implementation.
// Generated by nitrogen init. Fill in the method bodies.
#include "../../lib/src/generated/cpp/nitro_webgpu.native.g.h"

#include <string>

class HybridNitroWebgpuImpl final : public HybridNitroWebgpu {
public:
    // TODO: implement all pure-virtual methods declared in HybridNitroWebgpu
};

// GCC/Clang auto-registration via constructor attribute.
__attribute__((constructor))
static void nitro_auto_register() {
    nitro_webgpu_register_impl(new HybridNitroWebgpuImpl());
}
