// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.5.12
// Generated from: nitro_webgpu.native.dart
// NativeImpl: cpp — shared C++ virtual-dispatch bridge (no JNI / Swift).
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdlib.h>
#include <string>
#include <stdexcept>
#include "dart_api_dl.h"
#include "nitro_webgpu.bridge.g.h"
#include "nitro_webgpu.native.g.h"

extern "C" {
NITRO_EXPORT uint32_t nitro_webgpu_nitro_abi_version(void) {
    return 1;
}
NITRO_EXPORT const char* nitro_webgpu_nitro_bridge_checksum(void) {
    return "6a29b4e4a12dd166";
}
NITRO_EXPORT intptr_t nitro_webgpu_init_dart_api_dl(void* data) {
    return Dart_InitializeApiDL(data);
}
}

static thread_local NitroError g_nitro_error = { 0, nullptr, nullptr, nullptr, nullptr };

extern "C" {
NitroError* nitro_webgpu_get_error() { return &g_nitro_error; }
void nitro_webgpu_clear_error() {
    if (!g_nitro_error.hasError) { return; }
    g_nitro_error.hasError = 0;
    if (g_nitro_error.name)       { free((void*)g_nitro_error.name);       g_nitro_error.name       = nullptr; }
    if (g_nitro_error.message)    { free((void*)g_nitro_error.message);    g_nitro_error.message    = nullptr; }
    if (g_nitro_error.code)       { free((void*)g_nitro_error.code);       g_nitro_error.code       = nullptr; }
    if (g_nitro_error.stackTrace) { free((void*)g_nitro_error.stackTrace); g_nitro_error.stackTrace = nullptr; }
}
static void nitro_report_error(const char* name, const char* message, const char* code, const char* stack) {
    nitro_webgpu_clear_error();
    g_nitro_error.hasError = 1;
    g_nitro_error.name       = name    ? strdup(name)    : strdup("NativeException");
    g_nitro_error.message    = message ? strdup(message) : strdup("An unknown C++ exception occurred.");
    g_nitro_error.code       = code    ? strdup(code)    : nullptr;
    g_nitro_error.stackTrace = stack   ? strdup(stack)   : nullptr;
}
}

#include <atomic>
#include <memory>
#include <mutex>
#include <unordered_map>

using HybridNitroWebgpuFactory = std::function<std::shared_ptr<HybridNitroWebgpu>(const std::string&)>;
static std::unordered_map<int64_t, std::shared_ptr<HybridNitroWebgpu>>& _g_instances() {
    static std::unordered_map<int64_t, std::shared_ptr<HybridNitroWebgpu>> m;
    return m;
}
static std::mutex& _g_instances_mtx() {
    static std::mutex m;
    return m;
}
static std::atomic<int64_t>& _g_next_instance_id() {
    static std::atomic<int64_t> id{1};
    return id;
}
static HybridNitroWebgpuFactory& _g_factory() {
    static HybridNitroWebgpuFactory f;
    return f;
}

static std::shared_ptr<HybridNitroWebgpu> _nitro_get_instance(int64_t id) {
    std::lock_guard<std::mutex> _lk(_g_instances_mtx());
    auto it = _g_instances().find(id);
    return it != _g_instances().end() ? it->second : nullptr;
}

extern "C" {
void nitro_webgpu_register_factory(void* fn) {
    _g_factory() = *static_cast<HybridNitroWebgpuFactory*>(fn);
}
void nitro_webgpu_register_impl(HybridNitroWebgpu* impl) {
    std::lock_guard<std::mutex> _lk(_g_instances_mtx());
    if (impl) _g_instances()[0] = std::shared_ptr<HybridNitroWebgpu>(impl, [](HybridNitroWebgpu*){});
    else _g_instances().erase(0);
}
HybridNitroWebgpu* nitro_webgpu_get_impl() {
    auto ptr = _nitro_get_instance(0);
    return ptr ? ptr.get() : nullptr;
}
NITRO_EXPORT int64_t nitro_webgpu_create_instance(const char* key) {
    if (_g_factory()) {
        auto inst = _g_factory()(key ? key : "");
        if (!inst) return -1;
        std::lock_guard<std::mutex> _lk(_g_instances_mtx());
        int64_t id = ++_g_next_instance_id();
        _g_instances()[id] = std::move(inst);
        return id;
    }
    // Legacy: no factory registered — return 0 (single global impl slot)
    return 0;
}
NITRO_EXPORT void nitro_webgpu_destroy_instance(int64_t instanceId) {
    std::lock_guard<std::mutex> _lk(_g_instances_mtx());
    _g_instances().erase(instanceId);
}
NITRO_EXPORT void nitro_webgpu_nitro_free(void* ptr) { if (ptr) { free(ptr); } }
NITRO_EXPORT void* nitro_webgpu_nitro_alloc(size_t size) { return malloc(size); }
}

// S8 helper — writes error info to the out-param slot.
static void _nitro_out_err(NitroError* e, const char* name, const char* msg) {
    if (!e) return;
    e->hasError = 1;
    e->name       = name ? strdup(name) : nullptr;
    e->message    = msg  ? strdup(msg)  : nullptr;
    e->code       = nullptr;
    e->stackTrace = nullptr;
}

extern "C" {

void nitro_webgpu_init_instance(int64_t instanceId, void* options, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_webgpu_register_factory() or nitro_webgpu_register_impl()."); return; }
    try {
        NitroCppBuffer _buf_options = { (const uint8_t*)options + 4, (size_t)*(int32_t*)options };
        _impl->initInstance(_buf_options);
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

const char* nitro_webgpu_wgpu_version(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_out_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_webgpu_register_factory() or nitro_webgpu_register_impl()."); return nullptr; }
    try {
        std::string _res = _impl->wgpuVersion();
        return strdup(_res.c_str());
    } catch (const std::exception& e) {
        _nitro_out_err(_nitro_err, "CppException", e.what());
        return nullptr;
    } catch (...) {
        _nitro_out_err(_nitro_err, "CppException", "Unknown C++ exception");
        return nullptr;
    }
}

} // extern "C"
