// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.5.15
// Generated from: nitro_webgpu_present.native.dart
import Foundation
import Combine
#if canImport(NitroWebgpuPresentCpp)
import NitroWebgpuPresentCpp
#endif

@inline(__always)
private func _nitroStringFromCString(_ ptr: UnsafePointer<CChar>?) -> String {
    guard let ptr = ptr else { return "" }
    let len = Int(strlen(ptr))
    return String(decoding: UnsafeBufferPointer(start: UnsafeRawPointer(ptr).assumingMemoryBound(to: UInt8.self), count: len), as: UTF8.self)
}

@inline(__always)
private func _nitroStringOptFromCString(_ ptr: UnsafePointer<CChar>?) -> String? {
    ptr.map { p in
        let len = Int(strlen(p))
        return String(decoding: UnsafeBufferPointer(start: UnsafeRawPointer(p).assumingMemoryBound(to: UInt8.self), count: len), as: UTF8.self)
    }
}

@inline(__always)
private func _nitroStringToCString(_ s: String) -> UnsafeMutablePointer<CChar> {
    let utf8 = Array(s.utf8)
    let ptr = UnsafeMutablePointer<CChar>.allocate(capacity: utf8.count + 1)
    utf8.withUnsafeBytes { UnsafeMutableRawPointer(ptr).copyMemory(from: $0.baseAddress!, byteCount: utf8.count) }
    ptr[utf8.count] = 0
    return ptr
}

// --- @HybridRecord binary extensions (generated by Nitrogen) ---

/**
 * Protocol for the NitroWebgpuPresent module.
 * Conform to this in your Swift source code.
 * Nitro may call this implementation from any native thread.
 * Keep mutable state thread-safe or marshal work onto your own queue/actor.
 */
public protocol HybridNitroWebgpuPresentProtocol: AnyObject {
    // source: nitro_webgpu_present.native.dart:27
    func createPresenter(deviceAddress: Int64, widthPx: Int64, heightPx: Int64) -> Int64
    // source: nitro_webgpu_present.native.dart:30
    func flutterTextureId(token: Int64) -> Int64
    // source: nitro_webgpu_present.native.dart:36
    func acquireFrame(token: Int64) async throws -> Int64
    // source: nitro_webgpu_present.native.dart:42
    func acquireFrameSync(token: Int64) -> Int64
    // source: nitro_webgpu_present.native.dart:45
    func presentFrame(token: Int64) -> Void
    // source: nitro_webgpu_present.native.dart:49
    func presenterFormat(token: Int64) -> Int64
    // source: nitro_webgpu_present.native.dart:53
    func presenterUsesGpuPath(token: Int64) -> Bool
    // source: nitro_webgpu_present.native.dart:58
    func resizePresenter(token: Int64, widthPx: Int64, heightPx: Int64) -> Void
    // source: nitro_webgpu_present.native.dart:63
    func presenterSetSurfaceSize(token: Int64, widthPx: Int64, heightPx: Int64) -> Void
    // source: nitro_webgpu_present.native.dart:70
    func requestMaxRefreshRate() -> Double
    // source: nitro_webgpu_present.native.dart:75
    func destroyPresenter(token: Int64) async throws -> Void
}

public class NitroWebgpuPresentRegistry {
    public static var impl: HybridNitroWebgpuPresentProtocol?

    public static func register(_ impl: HybridNitroWebgpuPresentProtocol) {
        NitroWebgpuPresentRegistry.impl = impl
    }
}

// MARK: - C bridge stubs — exported as C symbols called by the generated .cpp shim

// source: nitro_webgpu_present.native.dart:27
@_cdecl("_nitro_webgpu_present_call_createPresenter")
public func _nitro_webgpu_present_call_createPresenter(_ deviceAddress: Int64, _ widthPx: Int64, _ heightPx: Int64) -> Int64 {
    guard let impl = NitroWebgpuPresentRegistry.impl else { return 0 }
    return impl.createPresenter(deviceAddress: deviceAddress, widthPx: widthPx, heightPx: heightPx)
}

// source: nitro_webgpu_present.native.dart:30
@_cdecl("_nitro_webgpu_present_call_flutterTextureId")
public func _nitro_webgpu_present_call_flutterTextureId(_ token: Int64) -> Int64 {
    guard let impl = NitroWebgpuPresentRegistry.impl else { return 0 }
    return impl.flutterTextureId(token: token)
}

// source: nitro_webgpu_present.native.dart:36
@_cdecl("_nitro_webgpu_present_call_acquireFrame")
public func _nitro_webgpu_present_call_acquireFrame(_ token: Int64, _ errPtr: Int64, _ dartPort: Int64) {
    let _errPtr = UnsafeMutablePointer<NitroError>(bitPattern: UInt(bitPattern: Int(errPtr)))
    guard let impl = NitroWebgpuPresentRegistry.impl else {
        var _null = Dart_CObject()
        _null.type = Dart_CObject_kNull
        Dart_PostCObject_DL(dartPort, &_null)
        return
    }
    Task.detached {
        do {
        let _result = try await impl.acquireFrame(token: token)
        var _obj = Dart_CObject()
        _obj.type = Dart_CObject_kInt64
        _obj.value.as_int64 = Int64(_result)
        Dart_PostCObject_DL(dartPort, &_obj)
        } catch {
            if let _errPtr = _errPtr {
                let _nsErr = error as NSError
                _errPtr.pointee.hasError = 1
                _errPtr.pointee.name = UnsafePointer(strdup(_nsErr.domain))
                _errPtr.pointee.message = UnsafePointer(strdup(_nsErr.localizedDescription))
            }
            var _null = Dart_CObject()
            _null.type = Dart_CObject_kNull
            Dart_PostCObject_DL(dartPort, &_null)
        }
    }
}

// source: nitro_webgpu_present.native.dart:42
@_cdecl("_nitro_webgpu_present_call_acquireFrameSync")
public func _nitro_webgpu_present_call_acquireFrameSync(_ token: Int64) -> Int64 {
    guard let impl = NitroWebgpuPresentRegistry.impl else { return 0 }
    return impl.acquireFrameSync(token: token)
}

// source: nitro_webgpu_present.native.dart:45
@_cdecl("_nitro_webgpu_present_call_presentFrame")
public func _nitro_webgpu_present_call_presentFrame(_ token: Int64) -> Void {
    NitroWebgpuPresentRegistry.impl?.presentFrame(token: token)
}

// source: nitro_webgpu_present.native.dart:49
@_cdecl("_nitro_webgpu_present_call_presenterFormat")
public func _nitro_webgpu_present_call_presenterFormat(_ token: Int64) -> Int64 {
    guard let impl = NitroWebgpuPresentRegistry.impl else { return 0 }
    return impl.presenterFormat(token: token)
}

// source: nitro_webgpu_present.native.dart:53
@_cdecl("_nitro_webgpu_present_call_presenterUsesGpuPath")
public func _nitro_webgpu_present_call_presenterUsesGpuPath(_ token: Int64) -> Int8 {
    return Int8((NitroWebgpuPresentRegistry.impl?.presenterUsesGpuPath(token: token) ?? false) ? 1 : 0)
}

// source: nitro_webgpu_present.native.dart:58
@_cdecl("_nitro_webgpu_present_call_resizePresenter")
public func _nitro_webgpu_present_call_resizePresenter(_ token: Int64, _ widthPx: Int64, _ heightPx: Int64) -> Void {
    NitroWebgpuPresentRegistry.impl?.resizePresenter(token: token, widthPx: widthPx, heightPx: heightPx)
}

// source: nitro_webgpu_present.native.dart:63
@_cdecl("_nitro_webgpu_present_call_presenterSetSurfaceSize")
public func _nitro_webgpu_present_call_presenterSetSurfaceSize(_ token: Int64, _ widthPx: Int64, _ heightPx: Int64) -> Void {
    NitroWebgpuPresentRegistry.impl?.presenterSetSurfaceSize(token: token, widthPx: widthPx, heightPx: heightPx)
}

// source: nitro_webgpu_present.native.dart:70
@_cdecl("_nitro_webgpu_present_call_requestMaxRefreshRate")
public func _nitro_webgpu_present_call_requestMaxRefreshRate() -> Double {
    guard let impl = NitroWebgpuPresentRegistry.impl else { return 0.0 }
    return impl.requestMaxRefreshRate()
}

// source: nitro_webgpu_present.native.dart:75
@_cdecl("_nitro_webgpu_present_call_destroyPresenter")
public func _nitro_webgpu_present_call_destroyPresenter(_ token: Int64, _ errPtr: Int64, _ dartPort: Int64) {
    let _errPtr = UnsafeMutablePointer<NitroError>(bitPattern: UInt(bitPattern: Int(errPtr)))
    guard let impl = NitroWebgpuPresentRegistry.impl else {
        var _null = Dart_CObject()
        _null.type = Dart_CObject_kNull
        Dart_PostCObject_DL(dartPort, &_null)
        return
    }
    Task.detached {
        do {
        try await impl.destroyPresenter(token: token)
        var _null = Dart_CObject()
        _null.type = Dart_CObject_kNull
        Dart_PostCObject_DL(dartPort, &_null)
        } catch {
            if let _errPtr = _errPtr {
                let _nsErr = error as NSError
                _errPtr.pointee.hasError = 1
                _errPtr.pointee.name = UnsafePointer(strdup(_nsErr.domain))
                _errPtr.pointee.message = UnsafePointer(strdup(_nsErr.localizedDescription))
            }
            var _null = Dart_CObject()
            _null.type = Dart_CObject_kNull
            Dart_PostCObject_DL(dartPort, &_null)
        }
    }
}

